<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DonationTypeTableSeeder extends Seeder
{
    /**
     * Auto generated seed file.
     */
    public function run(): void
    {
        DB::table('donation_type')->delete();

        DB::table('donation_type')->insert([
            0 => [
                'id' => 1,
                'label' => 'Retreat Funding',
                'value' => '4001.xx',
                'name' => 'Retreat Funding',
                'description' => 'Retreat Funding (4001.xx)',
                'is_default' => 0,
                'is_reserved' => 0,
                'is_active' => 1,
                'deleted_at' => null,
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            1 => [
                'id' => 11,
                'label' => 'Bookstore Revenue',
                'value' => '4030.01',
                'name' => 'Bookstore Revenue',
                'description' => 'Bookstore Revenue (4030.01)',
                'is_default' => 0,
                'is_reserved' => 0,
                'is_active' => 1,
                'deleted_at' => null,
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            2 => [
                'id' => 24,
                'label' => 'Miscellaneous',
                'value' => '4500.xx',
                'name' => 'Miscellaneous',
                'description' => 'Miscellaneous (4500.xx)',
                'is_default' => 0,
                'is_reserved' => 0,
                'is_active' => 1,
                'deleted_at' => null,
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            4 => [
                'id' => 115,
                'label' => 'Retreat Deposits',
                'value' => '2106.xx',
                'name' => 'Retreat Deposits',
                'description' => 'Retreat Deposits (2106.xx)',
                'is_default' => 0,
                'is_reserved' => 0,
                'is_active' => 1,
                'deleted_at' => null,
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            5 => [
                'id' => 6,
                'label' => 'AGC - Endowment',
                'value' => '2110',
                'name' => 'AGC - Endowment	2110',
                'description' => 'AGC - Endowment (2110)',
                'is_default' => 0,
                'is_reserved' => 0,
                'is_active' => 1,
                'deleted_at' => null,
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            6 => [
                'id' => 9,
                'label' => 'AGC - Buildings & Maintenance',
                'value' => '8800.05',
                'name' => 'AGC - Buildings & Maintenance',
                'description' => 'AGC - Buildings & Maintenance (8800.05)',
                'is_default' => 0,
                'is_reserved' => 0,
                'is_active' => 1,
                'deleted_at' => null,
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            7 => [
                'id' => 26,
                'label' => 'Memorials',
                'value' => '8800.04',
                'name' => 'Memorials',
                'description' => 'Memorials (8000.04)',
                'is_default' => 0,
                'is_reserved' => 0,
                'is_active' => 1,
                'deleted_at' => null,
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            8 => [
                'id' => 35,
                'label' => 'Gift Certificates - Funded',
                'value' => '2104',
                'name' => 'Gift Certificates - Funded',
                'description' => 'Gift Certificates - Funded (2104)',
                'is_default' => 0,
                'is_reserved' => 0,
                'is_active' => 1,
                'deleted_at' => null,
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            9 => [
                'id' => 36,
                'label' => 'Tips',
                'value' => '2200',
                'name' => 'Tips',
                'description' => 'Tips',
                'is_default' => 0,
                'is_reserved' => 0,
                'is_active' => 1,
                'deleted_at' => null,
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            10 => [
                'id' => 61,
                'label' => 'Capital Campaign',
                'value' => 'Assets',
                'name' => 'Capital Campaign',
                'description' => 'Capital Campaign - various fixed assets (1xxx.xx)',
                'is_default' => 0,
                'is_reserved' => 0,
                'is_active' => 1,
                'deleted_at' => null,
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            11 => [
                'id' => 102,
                'label' => 'Grants',
                'value' => '2109',
                'name' => 'Grants',
                'description' => 'Grants',
                'is_default' => 0,
                'is_reserved' => 0,
                'is_active' => 1,
                'deleted_at' => null,
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            12 => [
                'id' => 103,
                'label' => 'Flowers and Landscaping',
                'value' => '5130.05',
                'name' => 'Flowers and Landscaping',
                'description' => 'Flowers and Landscaping - reduces Grounds maintenance exenses (5130.05)',
                'is_default' => 0,
                'is_reserved' => 0,
                'is_active' => 1,
                'deleted_at' => null,
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            13 => [
                'id' => 116,
                'label' => 'Bank & Credit Card Fees',
                'value' => '5600.12',
                'name' => 'Bank & Credit Card Fees',
                'description' => 'Bank & Credit Card Fees (5600.12)',
                'is_default' => 0,
                'is_reserved' => 0,
                'is_active' => 1,
                'deleted_at' => null,
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            14 => [
                'id' => 119,
                'label' => 'AGC - Scholarships',
                'value' => '8800.03',
                'name' => 'AGC - Scholarships',
                'description' => 'Annual Giving Campaign - Scholarships (8800.03)',
                'is_default' => 0,
                'is_reserved' => 0,
                'is_active' => 1,
                'deleted_at' => null,
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            15 => [
                'id' => 127,
                'label' => 'North Texas Giving',
                'value' => '8000.01',
                'name' => 'North Texas Giving',
                'description' => 'North Texas Giving (8000.01)',
                'is_default' => 0,
                'is_reserved' => 0,
                'is_active' => 1,
                'deleted_at' => null,
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            16 => [
                'id' => 130,
                'label' => 'Donations',
                'value' => '8000.05',
                'name' => 'Donations',
                'description' => 'Donations (8000.05)',
                'is_default' => 0,
                'is_reserved' => 0,
                'is_active' => 1,
                'deleted_at' => null,
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            17 => [
                'id' => 131,
                'label' => 'AGC - General',
                'value' => '8800.01',
                'name' => 'AGC - General',
                'description' => 'Annual Giving Campaign - General (8800.01)',
                'is_default' => 0,
                'is_reserved' => 0,
                'is_active' => 1,
                'deleted_at' => null,
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            18 => [
                'id' => 132,
                'label' => 'Reimbursement offsetting expense',
                'value' => 'Expenses',
                'name' => 'Reimbursement offsetting expense',
                'description' => 'Reimbursement offsetting expense (5xxx)',
                'is_default' => 0,
                'is_reserved' => 0,
                'is_active' => 1,
                'deleted_at' => null,
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            19 => [
                'id' => 133,
                'label' => 'Rent Income',
                'value' => '4200',
                'name' => 'Rent Income',
                'description' => 'Rent Income from Jesuit Community (4200)',
                'is_default' => 0,
                'is_reserved' => 0,
                'is_active' => 1,
                'deleted_at' => null,
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            20 => [
                'id' => 134,
                'label' => 'Interest Income',
                'value' => '4100.xx',
                'name' => 'Interest Income',
                'description' => 'Interest Income (4100.xx)',
                'is_default' => 0,
                'is_reserved' => 0,
                'is_active' => 1,
                'deleted_at' => null,
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            21 => [
                'id' => 135,
                'label' => 'In-Kind Contribution Income',
                'value' => '8900',
                'name' => 'In-Kind Contribution Income',
                'description' => 'In-Kind Contribution Income (8900)',
                'is_default' => 0,
                'is_reserved' => 0,
                'is_active' => 1,
                'deleted_at' => null,
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
        ]);
    }
}
