<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EventTypeTableSeeder extends Seeder
{
    /**
     * Auto generated seed file.
     *
     * @return void
     */
    public function run()
    {
        DB::table('event_type')->delete();

        DB::table('event_type')->insert([
            0 => [
                'id' => 1,
                'label' => 'Conference',
                'value' => 'Conference',
                'name' => 'Conference',
                'description' => 'Conference',
                'is_default' => 0,
                'is_reserved' => 0,
                'is_active' => 1,
                'deleted_at' => null,
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            1 => [
                'id' => 2,
                'label' => 'Exhibition',
                'value' => 'Exhibition',
                'name' => 'Exhibition',
                'description' => 'Exhibition',
                'is_default' => 0,
                'is_reserved' => 0,
                'is_active' => 1,
                'deleted_at' => null,
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            2 => [
                'id' => 3,
                'label' => 'Fundraiser',
                'value' => 'Fundraiser',
                'name' => 'Fundraiser',
                'description' => 'Fundraiser',
                'is_default' => 0,
                'is_reserved' => 0,
                'is_active' => 1,
                'deleted_at' => null,
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            3 => [
                'id' => 4,
                'label' => 'Meeting',
                'value' => 'Meeting',
                'name' => 'Meeting',
                'description' => 'Meeting',
                'is_default' => 0,
                'is_reserved' => 0,
                'is_active' => 1,
                'deleted_at' => null,
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            4 => [
                'id' => 5,
                'label' => 'Performance',
                'value' => 'Performance',
                'name' => 'Performance',
                'description' => 'Performance',
                'is_default' => 0,
                'is_reserved' => 0,
                'is_active' => 1,
                'deleted_at' => null,
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            5 => [
                'id' => 6,
                'label' => 'Workshop',
                'value' => 'Workshop',
                'name' => 'Workshop',
                'description' => 'Workshop',
                'is_default' => 0,
                'is_reserved' => 0,
                'is_active' => 1,
                'deleted_at' => null,
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            6 => [
                'id' => 7,
                'label' => 'Ignatian',
                'value' => 'Ignatian',
                'name' => 'Ignatian',
                'description' => 'Ignatian Retreat',
                'is_default' => 1,
                'is_reserved' => 0,
                'is_active' => 1,
                'deleted_at' => null,
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            7 => [
                'id' => 8,
                'label' => 'Diocesan',
                'value' => 'Diocesan',
                'name' => 'Diocesan',
                'description' => 'Diocesan',
                'is_default' => 0,
                'is_reserved' => 0,
                'is_active' => 1,
                'deleted_at' => null,
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            8 => [
                'id' => 9,
                'label' => 'Other',
                'value' => 'Other',
                'name' => 'Other',
                'description' => 'Other',
                'is_default' => 0,
                'is_reserved' => 0,
                'is_active' => 1,
                'deleted_at' => null,
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            9 => [
                'id' => 10,
                'label' => 'Day',
                'value' => 'Day',
                'name' => 'Day',
                'description' => 'Day',
                'is_default' => 0,
                'is_reserved' => 0,
                'is_active' => 1,
                'deleted_at' => null,
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            10 => [
                'id' => 11,
                'label' => 'Contract',
                'value' => 'Contract',
                'name' => 'Contract',
                'description' => 'Contract',
                'is_default' => 0,
                'is_reserved' => 0,
                'is_active' => 1,
                'deleted_at' => null,
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            11 => [
                'id' => 12,
                'label' => 'Directed',
                'value' => 'Directed',
                'name' => 'Directed',
                'description' => 'Directed',
                'is_default' => 0,
                'is_reserved' => 0,
                'is_active' => 1,
                'deleted_at' => null,
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            12 => [
                'id' => 13,
                'label' => 'ISI',
                'value' => 'ISI',
                'name' => 'ISI',
                'description' => 'Events related to ISI',
                'is_default' => 0,
                'is_reserved' => 0,
                'is_active' => 1,
                'deleted_at' => null,
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            13 => [
                'id' => 14,
                'label' => 'Jesuit',
                'value' => 'Jesuit',
                'name' => 'Jesuit',
                'description' => 'Events sponsored by the Jesuits (Assistancy, Province, or other Jesuit ministry)',
                'is_default' => 0,
                'is_reserved' => 0,
                'is_active' => 1,
                'deleted_at' => null,
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
        ]);
    }
}
