<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class SsCustomFormFieldTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('ss_custom_form_field')->delete();
        
        \DB::table('ss_custom_form_field')->insert(array (
            0 => 
            array (
                'id' => 1,
                'form_id' => 2,
                'name' => 'Title',
                'sort_order' => 1,
                'type' => 'select',
                'variable_name' => 'title',
                'created_at' => NULL,
                'updated_at' => '2022-05-14 06:25:29',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'form_id' => 2,
                'name' => 'Name',
                'sort_order' => 2,
                'type' => 'name',
                'variable_name' => 'name',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'form_id' => 2,
                'name' => 'Address',
                'sort_order' => 3,
                'type' => 'address',
                'variable_name' => 'full_address',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'form_id' => 2,
                'name' => 'Mobile Phone',
                'sort_order' => 5,
                'type' => 'phone',
                'variable_name' => 'mobile_phone',
                'created_at' => NULL,
                'updated_at' => '2022-05-14 06:26:17',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'form_id' => 2,
                'name' => 'Home Phone',
                'sort_order' => 6,
                'type' => 'phone',
                'variable_name' => 'home_phone',
                'created_at' => NULL,
                'updated_at' => '2022-05-14 06:27:30',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'form_id' => 2,
                'name' => 'Email',
                'sort_order' => 4,
                'type' => 'email',
                'variable_name' => 'email',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'form_id' => 2,
                'name' => 'Date of Birth',
                'sort_order' => 14,
                'type' => 'date',
                'variable_name' => 'date_of_birth',
                'created_at' => NULL,
                'updated_at' => '2022-06-04 12:17:45',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'form_id' => 2,
                'name' => 'Emergency Contact',
                'sort_order' => 8,
                'type' => 'person',
                'variable_name' => 'emergency_contact',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'form_id' => 2,
                'name' => 'Emergency Contact Relationship',
                'sort_order' => 9,
                'type' => 'text',
                'variable_name' => 'emergency_contact_relationship',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'form_id' => 2,
                'name' => 'Emergency Contact Phone Number',
                'sort_order' => 10,
                'type' => 'phone',
                'variable_name' => 'emergency_contact_phone',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'form_id' => 2,
                'name' => 'Parish',
                'sort_order' => 15,
                'type' => 'text',
                'variable_name' => 'parish',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'form_id' => 2,
                'name' => 'Preferred Language',
                'sort_order' => 13,
                'type' => 'select',
                'variable_name' => 'preferred_language',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'form_id' => 2,
                'name' => 'How did you first hear about Montserrat?',
                'sort_order' => 13,
                'type' => 'select',
                'variable_name' => 'hear_about',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => '2022-05-01 22:37:36',
            ),
            13 => 
            array (
                'id' => 14,
                'form_id' => 2,
                'name' => 'If other, please elaborate:',
                'sort_order' => 14,
                'type' => 'text',
                'variable_name' => 'hear_other',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => '2022-05-01 22:37:58',
            ),
            14 => 
            array (
                'id' => 15,
                'form_id' => 2,
                'name' => 'How did you hear about this particular retreat?',
                'sort_order' => 15,
                'type' => 'select',
                'variable_name' => 'hear_retreat',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => '2022-05-01 22:38:04',
            ),
            15 => 
            array (
                'id' => 16,
                'form_id' => 2,
                'name' => 'If Retreat Ambassador, name of Ambassador?',
                'sort_order' => 16,
                'type' => 'text',
                'variable_name' => 'hear_ambassador',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => '2022-05-01 22:38:15',
            ),
            16 => 
            array (
                'id' => 17,
                'form_id' => 2,
                'name' => 'Room Preference',
                'sort_order' => 12,
                'type' => 'select',
                'variable_name' => 'room_preference',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'form_id' => 2,
                'name' => 'Dietary Restrictions, Food Allergies or Other Special Needs',
                'sort_order' => 11,
                'type' => 'textarea',
                'variable_name' => 'dietary',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'form_id' => 2,
                'name' => 'Comments / Questions',
                'sort_order' => 16,
                'type' => 'textarea',
                'variable_name' => 'comments',
                'created_at' => NULL,
                'updated_at' => '2022-05-21 11:29:49',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 21,
                'form_id' => 4,
                'name' => 'Título',
                'sort_order' => 1,
                'type' => 'select',
                'variable_name' => 'title',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 22,
                'form_id' => 4,
                'name' => 'Nombre/Apellido',
                'sort_order' => 2,
                'type' => 'name',
                'variable_name' => 'name',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 23,
                'form_id' => 4,
                'name' => 'Fecha de Nacimiento',
                'sort_order' => 14,
                'type' => 'date',
                'variable_name' => 'date_of_birth',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 24,
                'form_id' => 4,
                'name' => 'Dirección',
                'sort_order' => 3,
                'type' => 'address',
                'variable_name' => 'full_address',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 25,
                'form_id' => 4,
                'name' => 'Correo Electrónico',
                'sort_order' => 4,
                'type' => 'email',
                'variable_name' => 'email',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 26,
                'form_id' => 4,
                'name' => 'Número de Teléfono de Casa',
                'sort_order' => 6,
                'type' => 'phone',
                'variable_name' => 'home_phone',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 27,
                'form_id' => 4,
                'name' => 'Número de Teléfono Móvil',
                'sort_order' => 5,
                'type' => 'phone',
                'variable_name' => 'mobile_phone',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 28,
                'form_id' => 4,
                'name' => 'Número de Teléfono de Trabajo',
                'sort_order' => 7,
                'type' => 'phone',
                'variable_name' => 'work_phone',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 29,
                'form_id' => 4,
                'name' => 'Contacto de Emergencia',
                'sort_order' => 8,
                'type' => 'person',
                'variable_name' => 'emergency_contact',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 30,
                'form_id' => 4,
                'name' => 'Relación a Contacto de Emergencia',
                'sort_order' => 9,
                'type' => 'text',
                'variable_name' => 'emergency_contact_relationship',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 31,
                'form_id' => 4,
                'name' => 'Número de Teléfono de Contacto de Emergencia',
                'sort_order' => 10,
                'type' => 'phone',
                'variable_name' => 'emergency_contact_phone',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 32,
                'form_id' => 4,
                'name' => 'Parroquia',
                'sort_order' => 15,
                'type' => 'text',
                'variable_name' => 'parish',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 33,
                'form_id' => 4,
                'name' => 'Idioma Preferido',
                'sort_order' => 13,
                'type' => 'select',
                'variable_name' => 'preferred_language',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 34,
                'form_id' => 4,
                'name' => '¿Cómo se enteró de montserrat?',
                'sort_order' => 14,
                'type' => 'select',
                'variable_name' => 'hear_about',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => '2022-05-01 07:12:43',
            ),
            33 => 
            array (
                'id' => 35,
                'form_id' => 4,
                'name' => 'Si otro, por favor elabora',
                'sort_order' => 15,
                'type' => 'text',
                'variable_name' => 'hear_other',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => '2022-05-01 07:12:50',
            ),
            34 => 
            array (
                'id' => 36,
                'form_id' => 4,
                'name' => '¿Cómo se enteró de este retiro en particular?',
                'sort_order' => 16,
                'type' => 'select',
                'variable_name' => 'hear_retreat',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => '2022-05-01 07:12:55',
            ),
            35 => 
            array (
                'id' => 37,
                'form_id' => 4,
                'name' => 'Si es Embajador del retiro, ¿nombre del Embajador?',
                'sort_order' => 17,
                'type' => 'text',
                'variable_name' => 'hear_ambassador',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => '2022-05-01 07:13:01',
            ),
            36 => 
            array (
                'id' => 38,
                'form_id' => 4,
                'name' => 'Preferencia de Habitación',
                'sort_order' => 12,
                'type' => 'select',
                'variable_name' => 'room_preference',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 39,
                'form_id' => 4,
                'name' => 'Restricciones dietéticas, alergias a los alimentos u otras necesidades',
                'sort_order' => 11,
                'type' => 'textbox',
                'variable_name' => 'dietary',
                'created_at' => NULL,
                'updated_at' => '2022-05-16 15:40:13',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 40,
                'form_id' => 4,
                'name' => 'Comentarios / Preguntas',
                'sort_order' => 16,
                'type' => 'textbox',
                'variable_name' => 'comments',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 41,
                'form_id' => 4,
                'name' => 'Asistirá su cónyuge?',
                'sort_order' => 21,
                'type' => 'select',
                'variable_name' => 'is_couple',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => '2022-05-01 07:19:57',
            ),
            40 => 
            array (
                'id' => 42,
                'form_id' => 4,
                'name' => 'Título del Conyuge',
                'sort_order' => 17,
                'type' => 'select',
                'variable_name' => 'couple_title',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 43,
                'form_id' => 4,
                'name' => 'Nombre del Conyuge',
                'sort_order' => 18,
                'type' => 'person',
                'variable_name' => 'couple_name',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 44,
                'form_id' => 4,
                'name' => 'Número de Teléfono Móvil del Conyuge',
                'sort_order' => 20,
                'type' => 'phone',
                'variable_name' => 'couple_mobile_phone',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 45,
                'form_id' => 4,
                'name' => 'Correo electrónico del Conyuge',
                'sort_order' => 19,
                'type' => 'email',
                'variable_name' => 'couple_email',
                'created_at' => NULL,
                'updated_at' => '2022-05-16 15:38:00',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 46,
                'form_id' => 4,
                'name' => 'Fecha de nacimiento del Conyuge',
                'sort_order' => 25,
                'type' => 'date',
                'variable_name' => 'couple_date_of_birth',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 47,
                'form_id' => 5,
                'name' => 'Title',
                'sort_order' => 1,
                'type' => 'select',
                'variable_name' => 'title',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 48,
                'form_id' => 5,
                'name' => 'Name',
                'sort_order' => 2,
                'type' => 'name',
                'variable_name' => 'name',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 49,
                'form_id' => 5,
                'name' => 'Address',
                'sort_order' => 3,
                'type' => 'address',
                'variable_name' => 'full_address',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 50,
                'form_id' => 5,
                'name' => 'Mobile Phone',
                'sort_order' => 5,
                'type' => 'phone',
                'variable_name' => 'mobile_phone',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 51,
                'form_id' => 5,
                'name' => 'Home Phone',
                'sort_order' => 6,
                'type' => 'phone',
                'variable_name' => 'home_phone',
                'created_at' => NULL,
                'updated_at' => '2022-05-14 21:58:04',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 52,
                'form_id' => 5,
                'name' => 'Email',
                'sort_order' => 4,
                'type' => 'email',
                'variable_name' => 'email',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 53,
                'form_id' => 5,
                'name' => 'Date of Birth',
                'sort_order' => 14,
                'type' => 'date',
                'variable_name' => 'date_of_birth',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 54,
                'form_id' => 5,
                'name' => 'Emergency Contact',
                'sort_order' => 8,
                'type' => 'name',
                'variable_name' => 'emergency_contact',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 55,
                'form_id' => 5,
                'name' => 'Emergency Contact Relationship',
                'sort_order' => 9,
                'type' => 'text',
                'variable_name' => 'emergency_contact_relationship',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 56,
                'form_id' => 5,
                'name' => 'Emergency Contact Phone Number',
                'sort_order' => 10,
                'type' => 'phone',
                'variable_name' => 'emergency_contact_phone',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 57,
                'form_id' => 5,
                'name' => 'Parish',
                'sort_order' => 15,
                'type' => 'text',
                'variable_name' => 'parish',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 58,
                'form_id' => 5,
                'name' => 'Preferred Language',
                'sort_order' => 13,
                'type' => 'select',
                'variable_name' => 'preferred_language',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 59,
                'form_id' => 5,
                'name' => 'How did you hear about Montserrat',
                'sort_order' => 13,
                'type' => 'select',
                'variable_name' => 'hear_about',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => '2022-05-01 22:51:56',
            ),
            58 => 
            array (
                'id' => 60,
                'form_id' => 5,
                'name' => 'If "Other" please elaborate: ',
                'sort_order' => 14,
                'type' => 'text',
                'variable_name' => 'hear_other',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => '2022-05-01 22:52:02',
            ),
            59 => 
            array (
                'id' => 61,
                'form_id' => 5,
                'name' => 'How did you hear about this particular retreat?',
                'sort_order' => 15,
                'type' => 'select',
                'variable_name' => 'hear_retreat',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => '2022-05-01 22:52:07',
            ),
            60 => 
            array (
                'id' => 62,
                'form_id' => 5,
                'name' => 'If "Retreat Ambassador" please name them:',
                'sort_order' => 16,
                'type' => 'text',
                'variable_name' => 'hear_ambassador',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => '2022-05-01 22:52:13',
            ),
            61 => 
            array (
                'id' => 63,
                'form_id' => 5,
                'name' => 'Room Preference',
                'sort_order' => 12,
                'type' => 'select',
                'variable_name' => 'room_preference',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            62 => 
            array (
                'id' => 64,
                'form_id' => 5,
                'name' => 'Dietary Restrictions, Food Allergies, or Other Special Needs:',
                'sort_order' => 11,
                'type' => 'textbox',
                'variable_name' => 'dietary',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            63 => 
            array (
                'id' => 65,
                'form_id' => 5,
                'name' => 'Comments',
                'sort_order' => 16,
                'type' => 'textbox',
                'variable_name' => 'comments',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            64 => 
            array (
                'id' => 66,
                'form_id' => 5,
                'name' => 'Spouse\'s Name',
                'sort_order' => 18,
                'type' => 'name',
                'variable_name' => 'couple_name',
                'created_at' => NULL,
                'updated_at' => '2022-06-03 20:56:13',
                'deleted_at' => NULL,
            ),
            65 => 
            array (
                'id' => 67,
                'form_id' => 5,
                'name' => 'Spouse\'s Mobile Phone',
                'sort_order' => 20,
                'type' => 'phone',
                'variable_name' => 'couple_mobile_phone',
                'created_at' => NULL,
                'updated_at' => '2022-05-21 09:57:28',
                'deleted_at' => NULL,
            ),
            66 => 
            array (
                'id' => 68,
                'form_id' => 5,
                'name' => 'Spouse\'s Email',
                'sort_order' => 19,
                'type' => 'email',
                'variable_name' => 'couple_email',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            67 => 
            array (
                'id' => 69,
                'form_id' => 5,
                'name' => 'Spouse\'s Date of Birth',
                'sort_order' => 25,
                'type' => 'date',
                'variable_name' => 'couple_date_of_birth',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            68 => 
            array (
                'id' => 70,
                'form_id' => 5,
                'name' => 'Spouse\'s Emergency Contact',
                'sort_order' => 21,
                'type' => 'name',
                'variable_name' => 'couple_emergency_contact',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            69 => 
            array (
                'id' => 71,
                'form_id' => 5,
                'name' => 'Spouse\'s Emergency Contact Relationship',
                'sort_order' => 22,
                'type' => 'text',
                'variable_name' => 'couple_emergency_contact_relationship',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            70 => 
            array (
                'id' => 72,
                'form_id' => 5,
                'name' => 'Spouse\'s Emergency Contact Phone Number',
                'sort_order' => 23,
                'type' => 'phone',
                'variable_name' => 'couple_emergency_contact_phone',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            71 => 
            array (
                'id' => 73,
                'form_id' => 5,
                'name' => 'Spouse\'s Dietary Restrictions, Food Allergies, or Other Special Needs',
                'sort_order' => 24,
                'type' => 'textbox',
                'variable_name' => 'couple_dietary',
                'created_at' => NULL,
                'updated_at' => '2022-05-21 09:59:42',
                'deleted_at' => NULL,
            ),
            72 => 
            array (
                'id' => 74,
                'form_id' => 7,
                'name' => 'Purchaser\'s Name',
                'sort_order' => 2,
                'type' => 'name',
                'variable_name' => 'purchaser_name',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            73 => 
            array (
                'id' => 75,
                'form_id' => 7,
                'name' => 'Purchaser\'s Mobile Phone',
                'sort_order' => 5,
                'type' => 'phone',
                'variable_name' => 'purchaser_mobile_phone',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            74 => 
            array (
                'id' => 76,
                'form_id' => 7,
                'name' => 'Purchaser\'s Email',
                'sort_order' => 4,
                'type' => 'email',
                'variable_name' => 'purchaser_email',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            75 => 
            array (
                'id' => 77,
                'form_id' => 7,
                'name' => 'Purchaser\'s Address',
                'sort_order' => 3,
                'type' => 'address',
                'variable_name' => 'purchaser_address',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            76 => 
            array (
                'id' => 78,
                'form_id' => 7,
                'name' => 'Recipient\'s Name',
                'sort_order' => 8,
                'type' => 'name',
                'variable_name' => 'recipient_name',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            77 => 
            array (
                'id' => 79,
                'form_id' => 7,
                'name' => 'Recipient\'s Phone',
                'sort_order' => 10,
                'type' => 'phone',
                'variable_name' => 'recipient_phone',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            78 => 
            array (
                'id' => 80,
                'form_id' => 7,
                'name' => 'Recipient\'s Email',
                'sort_order' => 9,
                'type' => 'email',
                'variable_name' => 'recipient_email',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            79 => 
            array (
                'id' => 81,
                'form_id' => 8,
                'name' => 'Name',
                'sort_order' => 1,
                'type' => 'name',
                'variable_name' => 'name',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => '2022-05-15 11:04:11',
            ),
            80 => 
            array (
                'id' => 82,
                'form_id' => 8,
                'name' => 'Date Of Birth',
                'sort_order' => 2,
                'type' => 'date',
                'variable_name' => 'date_of_birth',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => '2022-05-15 11:04:11',
            ),
            81 => 
            array (
                'id' => 83,
                'form_id' => 8,
                'name' => 'Cell Phone',
                'sort_order' => 3,
                'type' => 'phone',
                'variable_name' => 'cell_phone',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => '2022-05-15 11:04:11',
            ),
            82 => 
            array (
                'id' => 84,
                'form_id' => 8,
                'name' => 'Email',
                'sort_order' => 4,
                'type' => 'email',
                'variable_name' => 'email',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => '2022-05-15 11:04:11',
            ),
            83 => 
            array (
                'id' => 85,
                'form_id' => 8,
                'name' => 'Emergency Contact',
                'sort_order' => 5,
                'type' => 'name',
                'variable_name' => 'emergency_contact',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => '2022-05-15 11:04:11',
            ),
            84 => 
            array (
                'id' => 86,
                'form_id' => 8,
                'name' => 'Emergency Contact Relationship',
                'sort_order' => 6,
                'type' => 'text',
                'variable_name' => 'emergency_contact_relationship',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => '2022-05-15 11:04:11',
            ),
            85 => 
            array (
                'id' => 87,
                'form_id' => 8,
                'name' => 'Emergency Contact Phone Number',
                'sort_order' => 7,
                'type' => 'phone',
                'variable_name' => 'emergency_contact_phone',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => '2022-05-15 11:04:11',
            ),
            86 => 
            array (
                'id' => 88,
                'form_id' => 8,
                'name' => 'How did you learn about this retreat?',
                'sort_order' => 8,
                'type' => 'select',
                'variable_name' => 'hear_about',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => '2022-05-15 11:04:11',
            ),
            87 => 
            array (
                'id' => 89,
                'form_id' => 8,
                'name' => 'If you are student, provide the name of your College/University',
                'sort_order' => 9,
                'type' => 'text',
                'variable_name' => 'college_name',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => '2022-05-15 11:04:11',
            ),
            88 => 
            array (
                'id' => 90,
                'form_id' => 8,
                'name' => 'Room Preference',
                'sort_order' => 10,
                'type' => 'select',
                'variable_name' => 'room_preference',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => '2022-05-15 11:04:11',
            ),
            89 => 
            array (
                'id' => 91,
                'form_id' => 8,
                'name' => 'Dietary Restriction, Food Allergies, or Other Special Needs',
                'sort_order' => 11,
                'type' => 'textbox',
                'variable_name' => 'dietary',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => '2022-05-15 11:04:11',
            ),
            90 => 
            array (
                'id' => 92,
                'form_id' => 8,
                'name' => 'Questions / Comments',
                'sort_order' => 12,
                'type' => 'textbox',
                'variable_name' => 'comments',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => '2022-05-15 11:04:11',
            ),
            91 => 
            array (
                'id' => 93,
                'form_id' => 6,
                'name' => 'Title',
                'sort_order' => 1,
                'type' => 'select',
                'variable_name' => 'title',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            92 => 
            array (
                'id' => 94,
                'form_id' => 6,
                'name' => 'Name',
                'sort_order' => 2,
                'type' => 'name',
                'variable_name' => 'name',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            93 => 
            array (
                'id' => 95,
                'form_id' => 6,
                'name' => 'Email',
                'sort_order' => 4,
                'type' => 'email',
                'variable_name' => 'email',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            94 => 
            array (
                'id' => 96,
                'form_id' => 6,
                'name' => 'Mobile Phone',
                'sort_order' => 5,
                'type' => 'phone',
                'variable_name' => 'mobile_phone',
                'created_at' => NULL,
                'updated_at' => '2022-05-15 19:48:58',
                'deleted_at' => NULL,
            ),
            95 => 
            array (
                'id' => 97,
                'form_id' => 6,
                'name' => 'Home Phone',
                'sort_order' => 6,
                'type' => 'phone',
                'variable_name' => 'home_phone',
                'created_at' => NULL,
                'updated_at' => '2022-05-15 19:49:12',
                'deleted_at' => NULL,
            ),
            96 => 
            array (
                'id' => 98,
                'form_id' => 6,
                'name' => 'Address',
                'sort_order' => 3,
                'type' => 'address',
                'variable_name' => 'full_address',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            97 => 
            array (
                'id' => 99,
                'form_id' => 6,
                'name' => 'Additional Names and Phone Numbers',
                'sort_order' => 9,
                'type' => 'text',
                'variable_name' => 'additional_names_and_phone_numbers',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            98 => 
            array (
                'id' => 100,
                'form_id' => 6,
                'name' => 'Comments / Questions',
                'sort_order' => 8,
                'type' => 'textbox',
                'variable_name' => 'comments',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            99 => 
            array (
                'id' => 101,
                'form_id' => 2,
                'name' => 'Work Phone',
                'sort_order' => 7,
                'type' => 'phone',
                'variable_name' => 'work_phone',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            100 => 
            array (
                'id' => 102,
                'form_id' => 5,
                'name' => 'Work Phone',
                'sort_order' => 7,
                'type' => 'phone',
                'variable_name' => 'work_phone',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            101 => 
            array (
                'id' => 103,
                'form_id' => 5,
                'name' => 'Spouse\'s Title',
                'sort_order' => 17,
                'type' => 'select',
                'variable_name' => 'couple_title',
                'created_at' => NULL,
                'updated_at' => '2022-05-14 22:01:32',
                'deleted_at' => NULL,
            ),
            102 => 
            array (
                'id' => 104,
                'form_id' => 4,
                'name' => 'Contacto de Emergencia del Conyuge',
                'sort_order' => 21,
                'type' => 'person',
                'variable_name' => 'couple_emergency_contact',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            103 => 
            array (
                'id' => 105,
                'form_id' => 4,
                'name' => 'Relación a Contacto de Emergencia del Conyuge',
                'sort_order' => 22,
                'type' => 'text',
                'variable_name' => 'couple_emergency_contact_relationship',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            104 => 
            array (
                'id' => 106,
                'form_id' => 4,
                'name' => 'Número de Teléfono de Contacto de Emergencia del Conyuge',
                'sort_order' => 23,
                'type' => 'phone',
                'variable_name' => 'couple_emergency_contact_phone',
                'created_at' => NULL,
                'updated_at' => '2022-05-16 15:36:40',
                'deleted_at' => NULL,
            ),
            105 => 
            array (
                'id' => 107,
                'form_id' => 4,
                'name' => 'Restricciones dietéticas, alergias a los alimentos u otras necesidades especiales del Conyuge',
                'sort_order' => 24,
                'type' => 'textarea',
                'variable_name' => 'couple_dietary',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            106 => 
            array (
                'id' => 108,
                'form_id' => 7,
                'name' => 'Purchaser\'s Title',
                'sort_order' => 1,
                'type' => 'select',
                'variable_name' => 'purchaser_title',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            107 => 
            array (
                'id' => 109,
                'form_id' => 7,
                'name' => 'Purchaser\'s Home Phone',
                'sort_order' => 6,
                'type' => 'phone',
                'variable_name' => 'purchaser_home_phone',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            108 => 
            array (
                'id' => 110,
                'form_id' => 7,
                'name' => 'Purchaser\'s Work Phone',
                'sort_order' => 7,
                'type' => 'phone',
                'variable_name' => 'purchaser_work_phone',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            109 => 
            array (
                'id' => 122,
                'form_id' => 9,
                'name' => 'Gift Certificate Number',
                'sort_order' => 1,
                'type' => 'text',
                'variable_name' => 'gift_certificate_number',
                'created_at' => '2022-05-15 19:16:32',
                'updated_at' => '2022-05-15 19:34:40',
                'deleted_at' => NULL,
            ),
            110 => 
            array (
                'id' => 123,
                'form_id' => 9,
                'name' => 'Which retreat would you like to attend?',
                'sort_order' => 2,
                'type' => 'select',
                'variable_name' => 'gift_certificate_retreat',
                'created_at' => '2022-05-15 19:20:22',
                'updated_at' => '2022-05-16 11:00:11',
                'deleted_at' => NULL,
            ),
            111 => 
            array (
                'id' => 124,
                'form_id' => 9,
                'name' => 'Title',
                'sort_order' => 3,
                'type' => 'select',
                'variable_name' => 'title',
                'created_at' => '2022-05-15 19:20:48',
                'updated_at' => '2022-05-15 19:20:48',
                'deleted_at' => NULL,
            ),
            112 => 
            array (
                'id' => 125,
                'form_id' => 9,
                'name' => 'Name',
                'sort_order' => 4,
                'type' => 'name',
                'variable_name' => 'name',
                'created_at' => '2022-05-15 19:21:21',
                'updated_at' => '2022-05-15 19:21:21',
                'deleted_at' => NULL,
            ),
            113 => 
            array (
                'id' => 126,
                'form_id' => 9,
                'name' => 'Address',
                'sort_order' => 5,
                'type' => 'address',
                'variable_name' => 'full_address',
                'created_at' => '2022-05-15 19:21:42',
                'updated_at' => '2022-05-15 19:21:42',
                'deleted_at' => NULL,
            ),
            114 => 
            array (
                'id' => 127,
                'form_id' => 9,
                'name' => 'Email',
                'sort_order' => 6,
                'type' => 'email',
                'variable_name' => 'email',
                'created_at' => '2022-05-15 19:22:02',
                'updated_at' => '2022-05-15 19:22:02',
                'deleted_at' => NULL,
            ),
            115 => 
            array (
                'id' => 128,
                'form_id' => 9,
                'name' => 'Mobile Phone',
                'sort_order' => 7,
                'type' => 'phone',
                'variable_name' => 'mobile_phone',
                'created_at' => '2022-05-15 19:22:42',
                'updated_at' => '2022-05-15 19:22:42',
                'deleted_at' => NULL,
            ),
            116 => 
            array (
                'id' => 129,
                'form_id' => 9,
                'name' => 'Home Phone',
                'sort_order' => 8,
                'type' => 'phone',
                'variable_name' => 'home_phone',
                'created_at' => '2022-05-15 19:22:58',
                'updated_at' => '2022-05-15 19:22:58',
                'deleted_at' => NULL,
            ),
            117 => 
            array (
                'id' => 130,
                'form_id' => 9,
                'name' => 'Work Phone',
                'sort_order' => 9,
                'type' => 'phone',
                'variable_name' => 'work_phone',
                'created_at' => '2022-05-15 19:23:13',
                'updated_at' => '2022-05-15 19:23:13',
                'deleted_at' => NULL,
            ),
            118 => 
            array (
                'id' => 131,
                'form_id' => 9,
                'name' => 'Emergency Contact',
                'sort_order' => 10,
                'type' => 'name',
                'variable_name' => 'emergency_contact',
                'created_at' => '2022-05-15 19:23:48',
                'updated_at' => '2022-05-15 19:23:48',
                'deleted_at' => NULL,
            ),
            119 => 
            array (
                'id' => 132,
                'form_id' => 9,
                'name' => 'Emergency Contact Relationship',
                'sort_order' => 11,
                'type' => 'text',
                'variable_name' => 'emergency_contact_relationship',
                'created_at' => '2022-05-15 19:24:26',
                'updated_at' => '2022-05-15 19:24:26',
                'deleted_at' => NULL,
            ),
            120 => 
            array (
                'id' => 133,
                'form_id' => 9,
                'name' => 'Emergency Contact Phone',
                'sort_order' => 12,
                'type' => 'phone',
                'variable_name' => 'emergency_contact_phone',
                'created_at' => '2022-05-15 19:25:00',
                'updated_at' => '2022-05-15 19:25:00',
                'deleted_at' => NULL,
            ),
            121 => 
            array (
                'id' => 134,
                'form_id' => 9,
                'name' => 'Dietary Restrictions, Food Allergies or Other Special Needs',
                'sort_order' => 13,
                'type' => 'textarea',
                'variable_name' => 'dietary',
                'created_at' => '2022-05-15 19:25:47',
                'updated_at' => '2022-05-15 19:25:55',
                'deleted_at' => NULL,
            ),
            122 => 
            array (
                'id' => 135,
                'form_id' => 9,
                'name' => 'Room Preference',
                'sort_order' => 14,
                'type' => 'select',
                'variable_name' => 'room_preference',
                'created_at' => '2022-05-15 19:26:37',
                'updated_at' => '2022-05-15 19:26:37',
                'deleted_at' => NULL,
            ),
            123 => 
            array (
                'id' => 136,
                'form_id' => 9,
                'name' => 'Preferred Language',
                'sort_order' => 15,
                'type' => 'select',
                'variable_name' => 'preferred_language',
                'created_at' => '2022-05-15 19:27:16',
                'updated_at' => '2022-05-15 19:27:16',
                'deleted_at' => NULL,
            ),
            124 => 
            array (
                'id' => 137,
                'form_id' => 9,
                'name' => 'Date of Birth',
                'sort_order' => 16,
                'type' => 'date',
                'variable_name' => 'date_of_birth',
                'created_at' => '2022-05-15 19:27:45',
                'updated_at' => '2022-05-15 19:27:45',
                'deleted_at' => NULL,
            ),
            125 => 
            array (
                'id' => 138,
                'form_id' => 9,
                'name' => 'Parish',
                'sort_order' => 17,
                'type' => 'text',
                'variable_name' => 'parish',
                'created_at' => '2022-05-15 19:28:13',
                'updated_at' => '2022-05-15 19:28:23',
                'deleted_at' => NULL,
            ),
            126 => 
            array (
                'id' => 139,
                'form_id' => 9,
                'name' => 'Comments / Questions',
                'sort_order' => 18,
                'type' => 'textarea',
                'variable_name' => 'comments',
                'created_at' => '2022-05-15 19:29:13',
                'updated_at' => '2022-05-15 19:29:13',
                'deleted_at' => NULL,
            ),
            127 => 
            array (
                'id' => 140,
                'form_id' => 10,
                'name' => 'Número de certificado de regalo',
                'sort_order' => 1,
                'type' => 'text',
                'variable_name' => 'gift_certificate_number',
                'created_at' => '2022-05-15 19:32:09',
                'updated_at' => '2022-05-15 19:32:09',
                'deleted_at' => NULL,
            ),
            128 => 
            array (
                'id' => 141,
                'form_id' => 10,
                'name' => '¿A qué retiro le gustaría asistir?',
                'sort_order' => 2,
                'type' => 'select',
                'variable_name' => 'gift_certificate_retreat',
                'created_at' => '2022-05-15 19:33:30',
                'updated_at' => '2022-05-16 11:00:40',
                'deleted_at' => NULL,
            ),
            129 => 
            array (
                'id' => 144,
                'form_id' => 10,
                'name' => 'Título',
                'sort_order' => 3,
                'type' => 'select',
                'variable_name' => 'title',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            130 => 
            array (
                'id' => 145,
                'form_id' => 10,
                'name' => 'Nombre/Apellido',
                'sort_order' => 4,
                'type' => 'name',
                'variable_name' => 'name',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            131 => 
            array (
                'id' => 146,
                'form_id' => 10,
                'name' => 'Dirección',
                'sort_order' => 5,
                'type' => 'address',
                'variable_name' => 'full_address',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            132 => 
            array (
                'id' => 147,
                'form_id' => 10,
                'name' => 'Correo electrónico',
                'sort_order' => 6,
                'type' => 'email',
                'variable_name' => 'email',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            133 => 
            array (
                'id' => 148,
                'form_id' => 10,
                'name' => '
Número de Teléfono Móvil',
                'sort_order' => 7,
                'type' => 'phone',
                'variable_name' => 'mobile_phone',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            134 => 
            array (
                'id' => 149,
                'form_id' => 10,
                'name' => 'Número de Teléfono de Casa',
                'sort_order' => 8,
                'type' => 'phone',
                'variable_name' => 'home_phone',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            135 => 
            array (
                'id' => 150,
                'form_id' => 10,
                'name' => 'Número de Teléfono de Trabajo',
                'sort_order' => 9,
                'type' => 'phone',
                'variable_name' => 'work_phone',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            136 => 
            array (
                'id' => 151,
                'form_id' => 10,
                'name' => '
Contacto de Emergencia',
                'sort_order' => 10,
                'type' => 'name',
                'variable_name' => 'emergency_contact',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            137 => 
            array (
                'id' => 152,
                'form_id' => 10,
                'name' => '
Relación a Contacto de Emergencia',
                'sort_order' => 11,
                'type' => 'text',
                'variable_name' => 'emergency_contact_relationship',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            138 => 
            array (
                'id' => 153,
                'form_id' => 10,
                'name' => '
Número de Teléfono de Contacto de Emergencia ',
                'sort_order' => 12,
                'type' => 'phone',
                'variable_name' => 'emergency_contact_phone',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            139 => 
            array (
                'id' => 154,
                'form_id' => 10,
                'name' => 'Restricciones dietéticas, alergias a los alimentos u otras necesidades especiales ',
                'sort_order' => 13,
                'type' => 'textarea',
                'variable_name' => 'dietary',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            140 => 
            array (
                'id' => 155,
                'form_id' => 10,
                'name' => 'Preferencia de Habitación',
                'sort_order' => 14,
                'type' => 'select',
                'variable_name' => 'room_preference',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            141 => 
            array (
                'id' => 156,
                'form_id' => 10,
                'name' => 'Idioma preferido',
                'sort_order' => 15,
                'type' => 'select',
                'variable_name' => 'preferred_language',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            142 => 
            array (
                'id' => 157,
                'form_id' => 10,
                'name' => 'Fecha de Nacimiento',
                'sort_order' => 16,
                'type' => 'date',
                'variable_name' => 'date_of_birth',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            143 => 
            array (
                'id' => 158,
                'form_id' => 10,
                'name' => 'Parroquia',
                'sort_order' => 17,
                'type' => 'text',
                'variable_name' => 'parish',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            144 => 
            array (
                'id' => 159,
                'form_id' => 10,
                'name' => 'Comentarios / Preguntas',
                'sort_order' => 18,
                'type' => 'textarea',
                'variable_name' => 'comments',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            145 => 
            array (
                'id' => 173,
                'form_id' => 6,
                'name' => 'Work Phone',
                'sort_order' => 7,
                'type' => 'phone',
                'variable_name' => 'work_phone',
                'created_at' => '2022-05-15 19:53:57',
                'updated_at' => '2022-05-15 19:53:57',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}