<?php

use Illuminate\Database\Seeder;

class GroupTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('group')->delete();
        
        \DB::table('group')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Innkeeper',
                'title' => 'Innkeepers',
                'description' => 'Group of current retreat innkeepers',
                'source' => NULL,
                'saved_search_id' => NULL,
                'is_active' => 1,
                'visibility' => 'User and User Admin Only',
                'where_clause' => NULL,
                'select_tables' => NULL,
                'where_tables' => NULL,
                'group_type' => NULL,
                'cache_date' => NULL,
                'refresh_date' => NULL,
                'parents' => NULL,
                'children' => NULL,
                'is_hidden' => 0,
                'is_reserved' => 0,
                'created_id' => NULL,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Director',
                'title' => 'Directors',
                'description' => 'Retreat Directors',
                'source' => NULL,
                'saved_search_id' => NULL,
                'is_active' => 1,
                'visibility' => 'User and User Admin Only',
                'where_clause' => NULL,
                'select_tables' => NULL,
                'where_tables' => NULL,
                'group_type' => NULL,
                'cache_date' => NULL,
                'refresh_date' => NULL,
                'parents' => NULL,
                'children' => NULL,
                'is_hidden' => 0,
                'is_reserved' => 0,
                'created_id' => NULL,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Assistant',
                'title' => 'Assistants',
                'description' => 'Retreat Assistants',
                'source' => NULL,
                'saved_search_id' => NULL,
                'is_active' => 1,
                'visibility' => 'User and User Admin Only',
                'where_clause' => NULL,
                'select_tables' => NULL,
                'where_tables' => NULL,
                'group_type' => NULL,
                'cache_date' => NULL,
                'refresh_date' => NULL,
                'parents' => NULL,
                'children' => NULL,
                'is_hidden' => 0,
                'is_reserved' => 0,
                'created_id' => NULL,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Bishop',
                'title' => 'Bishops',
                'description' => 'Bishops',
                'source' => NULL,
                'saved_search_id' => NULL,
                'is_active' => 1,
                'visibility' => 'User and User Admin Only',
                'where_clause' => NULL,
                'select_tables' => NULL,
                'where_tables' => NULL,
                'group_type' => NULL,
                'cache_date' => NULL,
                'refresh_date' => NULL,
                'parents' => NULL,
                'children' => NULL,
                'is_hidden' => 0,
                'is_reserved' => 0,
                'created_id' => NULL,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Priest',
                'title' => 'Priests',
                'description' => 'Priests',
                'source' => NULL,
                'saved_search_id' => NULL,
                'is_active' => 1,
                'visibility' => 'User and User Admin Only',
                'where_clause' => NULL,
                'select_tables' => NULL,
                'where_tables' => NULL,
                'group_type' => NULL,
                'cache_date' => NULL,
                'refresh_date' => NULL,
                'parents' => NULL,
                'children' => NULL,
                'is_hidden' => 0,
                'is_reserved' => 0,
                'created_id' => NULL,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Deacon',
                'title' => 'Deacons',
                'description' => 'Deacons',
                'source' => NULL,
                'saved_search_id' => NULL,
                'is_active' => 1,
                'visibility' => 'User and User Admin Only',
                'where_clause' => NULL,
                'select_tables' => NULL,
                'where_tables' => NULL,
                'group_type' => NULL,
                'cache_date' => NULL,
                'refresh_date' => NULL,
                'parents' => NULL,
                'children' => NULL,
                'is_hidden' => 0,
                'is_reserved' => 0,
                'created_id' => NULL,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Jesuit',
                'title' => 'Jesuits',
                'description' => 'Jesuits',
                'source' => NULL,
                'saved_search_id' => NULL,
                'is_active' => 1,
                'visibility' => 'User and User Admin Only',
                'where_clause' => NULL,
                'select_tables' => NULL,
                'where_tables' => NULL,
                'group_type' => NULL,
                'cache_date' => NULL,
                'refresh_date' => NULL,
                'parents' => NULL,
                'children' => NULL,
                'is_hidden' => 0,
                'is_reserved' => 0,
                'created_id' => NULL,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Provincial',
                'title' => 'Provincials',
                'description' => 'Provincials',
                'source' => NULL,
                'saved_search_id' => NULL,
                'is_active' => 1,
                'visibility' => 'User and User Admin Only',
                'where_clause' => NULL,
                'select_tables' => NULL,
                'where_tables' => NULL,
                'group_type' => NULL,
                'cache_date' => NULL,
                'refresh_date' => NULL,
                'parents' => NULL,
                'children' => NULL,
                'is_hidden' => 0,
                'is_reserved' => 0,
                'created_id' => NULL,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Superior',
                'title' => 'Superiors',
                'description' => 'Superiors',
                'source' => NULL,
                'saved_search_id' => NULL,
                'is_active' => 1,
                'visibility' => 'User and User Admin Only',
                'where_clause' => NULL,
                'select_tables' => NULL,
                'where_tables' => NULL,
                'group_type' => NULL,
                'cache_date' => NULL,
                'refresh_date' => NULL,
                'parents' => NULL,
                'children' => NULL,
                'is_hidden' => 0,
                'is_reserved' => 0,
                'created_id' => NULL,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Pastor',
                'title' => 'Pastors',
                'description' => 'Pastors',
                'source' => NULL,
                'saved_search_id' => NULL,
                'is_active' => 1,
                'visibility' => 'User and User Admin Only',
                'where_clause' => NULL,
                'select_tables' => NULL,
                'where_tables' => NULL,
                'group_type' => NULL,
                'cache_date' => NULL,
                'refresh_date' => NULL,
                'parents' => NULL,
                'children' => NULL,
                'is_hidden' => 0,
                'is_reserved' => 0,
                'created_id' => NULL,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'Captain',
                'title' => 'Captains',
                'description' => 'Captains',
                'source' => NULL,
                'saved_search_id' => NULL,
                'is_active' => 1,
                'visibility' => 'User and User Admin Only',
                'where_clause' => NULL,
                'select_tables' => NULL,
                'where_tables' => NULL,
                'group_type' => NULL,
                'cache_date' => NULL,
                'refresh_date' => NULL,
                'parents' => NULL,
                'children' => NULL,
                'is_hidden' => 0,
                'is_reserved' => 0,
                'created_id' => NULL,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'Board member',
                'title' => 'Board members',
                'description' => 'Board member',
                'source' => NULL,
                'saved_search_id' => NULL,
                'is_active' => 1,
                'visibility' => 'User and User Admin Only',
                'where_clause' => NULL,
                'select_tables' => NULL,
                'where_tables' => NULL,
                'group_type' => NULL,
                'cache_date' => NULL,
                'refresh_date' => NULL,
                'parents' => NULL,
                'children' => NULL,
                'is_hidden' => 0,
                'is_reserved' => 0,
                'created_id' => NULL,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'Staff',
                'title' => 'Staff',
                'description' => 'Staff',
                'source' => NULL,
                'saved_search_id' => NULL,
                'is_active' => 1,
                'visibility' => 'User and User Admin Only',
                'where_clause' => NULL,
                'select_tables' => NULL,
                'where_tables' => NULL,
                'group_type' => NULL,
                'cache_date' => NULL,
                'refresh_date' => NULL,
                'parents' => NULL,
                'children' => NULL,
                'is_hidden' => 0,
                'is_reserved' => 0,
                'created_id' => NULL,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Volunteer',
                'title' => 'Volunteer',
                'description' => 'Group of volunteers',
                'source' => NULL,
                'saved_search_id' => NULL,
                'is_active' => 1,
                'visibility' => 'User and User Admin Only',
                'where_clause' => NULL,
                'select_tables' => NULL,
                'where_tables' => NULL,
                'group_type' => NULL,
                'cache_date' => NULL,
                'refresh_date' => NULL,
                'parents' => NULL,
                'children' => NULL,
                'is_hidden' => 0,
                'is_reserved' => 0,
                'created_id' => NULL,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'Stewards',
                'title' => 'Stewards',
                'description' => 'Good Stewards of Montserrat',
                'source' => NULL,
                'saved_search_id' => NULL,
                'is_active' => 1,
                'visibility' => 'User and User Admin Only',
                'where_clause' => NULL,
                'select_tables' => NULL,
                'where_tables' => NULL,
                'group_type' => NULL,
                'cache_date' => NULL,
                'refresh_date' => NULL,
                'parents' => NULL,
                'children' => NULL,
                'is_hidden' => NULL,
                'is_reserved' => NULL,
                'created_id' => NULL,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2016-09-29 17:40:53',
                'updated_at' => '2016-09-29 17:40:53',
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'Runner',
                'title' => 'Runner',
                'description' => 'Runners',
                'source' => NULL,
                'saved_search_id' => NULL,
                'is_active' => 1,
                'visibility' => 'User and User Admin Only',
                'where_clause' => NULL,
                'select_tables' => NULL,
                'where_tables' => NULL,
                'group_type' => NULL,
                'cache_date' => NULL,
                'refresh_date' => NULL,
                'parents' => NULL,
                'children' => NULL,
                'is_hidden' => NULL,
                'is_reserved' => NULL,
                'created_id' => NULL,
                'deleted_at' => '2017-05-04 13:31:09',
                'remember_token' => NULL,
                'created_at' => '2017-05-04 13:27:33',
                'updated_at' => '2017-05-04 13:31:09',
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'HLM2017',
                'title' => 'HLM2017',
                'description' => 'Hacia una Libertad Mayor 2017 group that meets to do a 19th Annotation retreat in Spanish on Wednesday evenings',
                'source' => NULL,
                'saved_search_id' => NULL,
                'is_active' => 1,
                'visibility' => 'User and User Admin Only',
                'where_clause' => NULL,
                'select_tables' => NULL,
                'where_tables' => NULL,
                'group_type' => NULL,
                'cache_date' => NULL,
                'refresh_date' => NULL,
                'parents' => NULL,
                'children' => NULL,
                'is_hidden' => NULL,
                'is_reserved' => NULL,
                'created_id' => NULL,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2017-10-10 11:58:55',
                'updated_at' => '2017-10-10 11:58:55',
            ),
        ));
        
        
    }
}