<?php

use Illuminate\Database\Seeder;

class LanguageTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('language')->delete();
        
        \DB::table('language')->insert(array (
            0 => 
            array (
                'id' => 1,
                'label' => 'Abkhaz',
                'value' => 'ab',
                'name' => 'ab_GE',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 1,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'label' => 'Afar',
                'value' => 'aa',
                'name' => 'aa_ET',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 2,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'label' => 'Afrikaans',
                'value' => 'af',
                'name' => 'af_ZA',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 3,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'label' => 'Akan',
                'value' => 'ak',
                'name' => 'ak_GH',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 4,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'label' => 'Albanian',
                'value' => 'sq',
                'name' => 'sq_AL',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 5,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'label' => 'Amharic',
                'value' => 'am',
                'name' => 'am_ET',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 6,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'label' => 'Arabic',
                'value' => 'ar',
                'name' => 'ar_EG',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 7,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'label' => 'Aragonese',
                'value' => 'an',
                'name' => 'an_ES',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 8,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'label' => 'Armenian',
                'value' => 'hy',
                'name' => 'hy_AM',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 9,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'label' => 'Assamese',
                'value' => 'as',
                'name' => 'as_IN',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 10,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'label' => 'Avaric',
                'value' => 'av',
                'name' => 'av_RU',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 11,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'label' => 'Avestan',
                'value' => 'ae',
                'name' => 'ae_XX',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 12,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'label' => 'Aymara',
                'value' => 'ay',
                'name' => 'ay_BO',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 13,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'label' => 'Azerbaijani',
                'value' => 'az',
                'name' => 'az_AZ',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 14,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'label' => 'Bambara',
                'value' => 'bm',
                'name' => 'bm_ML',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 15,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'label' => 'Bashkir',
                'value' => 'ba',
                'name' => 'ba_RU',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 16,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'label' => 'Basque',
                'value' => 'eu',
                'name' => 'eu_ES',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 17,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'label' => 'Belarusian',
                'value' => 'be',
                'name' => 'be_BY',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 18,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'label' => 'Bengali',
                'value' => 'bn',
                'name' => 'bn_BD',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 19,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'label' => 'Bihari',
                'value' => 'bh',
                'name' => 'bh_IN',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 20,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'label' => 'Bislama',
                'value' => 'bi',
                'name' => 'bi_VU',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 21,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'label' => 'Bosnian',
                'value' => 'bs',
                'name' => 'bs_BA',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 22,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'label' => 'Breton',
                'value' => 'br',
                'name' => 'br_FR',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 23,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'label' => 'Bulgarian',
                'value' => 'bg',
                'name' => 'bg_BG',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 24,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'label' => 'Burmese',
                'value' => 'my',
                'name' => 'my_MM',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 25,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'label' => 'Catalan; Valencian',
                'value' => 'ca',
                'name' => 'ca_ES',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 26,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'label' => 'Chamorro',
                'value' => 'ch',
                'name' => 'ch_GU',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 27,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'label' => 'Chechen',
                'value' => 'ce',
                'name' => 'ce_RU',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 28,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'label' => 'Chichewa; Chewa; Nyanja',
                'value' => 'ny',
                'name' => 'ny_MW',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 29,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
            'label' => 'Chinese (China)',
                'value' => 'zh',
                'name' => 'zh_CN',
                'is_active' => 1,
                'is_default' => 0,
                'weight' => 30,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
            'label' => 'Chinese (Taiwan)',
                'value' => 'zh',
                'name' => 'zh_TW',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 31,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'label' => 'Chuvash',
                'value' => 'cv',
                'name' => 'cv_RU',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 32,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'label' => 'Cornish',
                'value' => 'kw',
                'name' => 'kw_GB',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 33,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'label' => 'Corsican',
                'value' => 'co',
                'name' => 'co_FR',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 34,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'label' => 'Cree',
                'value' => 'cr',
                'name' => 'cr_CA',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 35,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'label' => 'Croatian',
                'value' => 'hr',
                'name' => 'hr_HR',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 36,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'label' => 'Czech',
                'value' => 'cs',
                'name' => 'cs_CZ',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 37,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'label' => 'Danish',
                'value' => 'da',
                'name' => 'da_DK',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 38,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'label' => 'Divehi; Dhivehi; Maldivian;',
                'value' => 'dv',
                'name' => 'dv_MV',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 39,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'label' => 'Dutch',
                'value' => 'nl',
                'name' => 'nl_NL',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 40,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'label' => 'Dzongkha',
                'value' => 'dz',
                'name' => 'dz_BT',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 41,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
            'label' => 'English (Australia)',
                'value' => 'en',
                'name' => 'en_AU',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 42,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
            'label' => 'English (Canada)',
                'value' => 'en',
                'name' => 'en_CA',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 43,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
            'label' => 'English (United Kingdom)',
                'value' => 'en',
                'name' => 'en_GB',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 44,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
            'label' => 'English (United States)',
                'value' => 'en',
                'name' => 'en_US',
                'is_active' => 1,
                'is_default' => 1,
                'weight' => 45,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'label' => 'Esperanto',
                'value' => 'eo',
                'name' => 'eo_XX',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 46,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'label' => 'Estonian',
                'value' => 'et',
                'name' => 'et_EE',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 47,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'label' => 'Ewe',
                'value' => 'ee',
                'name' => 'ee_GH',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 48,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'label' => 'Faroese',
                'value' => 'fo',
                'name' => 'fo_FO',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 49,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'label' => 'Fijian',
                'value' => 'fj',
                'name' => 'fj_FJ',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 50,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'label' => 'Finnish',
                'value' => 'fi',
                'name' => 'fi_FI',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 51,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
            'label' => 'French (Canada)',
                'value' => 'fr',
                'name' => 'fr_CA',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 52,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
            'label' => 'French (France)',
                'value' => 'fr',
                'name' => 'fr_FR',
                'is_active' => 1,
                'is_default' => 0,
                'weight' => 53,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'label' => 'Fula; Fulah; Pulaar; Pular',
                'value' => 'ff',
                'name' => 'ff_SN',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 54,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'label' => 'Galician',
                'value' => 'gl',
                'name' => 'gl_ES',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 55,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'label' => 'Georgian',
                'value' => 'ka',
                'name' => 'ka_GE',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 56,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'label' => 'German',
                'value' => 'de',
                'name' => 'de_DE',
                'is_active' => 1,
                'is_default' => 0,
                'weight' => 57,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
            'label' => 'German (Swiss)',
                'value' => 'de',
                'name' => 'de_CH',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 58,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'label' => 'Greek, Modern',
                'value' => 'el',
                'name' => 'el_GR',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 59,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'label' => 'Guaraní',
                'value' => 'gn',
                'name' => 'gn_PY',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 60,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'label' => 'Gujarati',
                'value' => 'gu',
                'name' => 'gu_IN',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 61,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'label' => 'Haitian; Haitian Creole',
                'value' => 'ht',
                'name' => 'ht_HT',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 62,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'label' => 'Hausa',
                'value' => 'ha',
                'name' => 'ha_NG',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 63,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
            'label' => 'Hebrew (modern)',
                'value' => 'he',
                'name' => 'he_IL',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 64,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'label' => 'Herero',
                'value' => 'hz',
                'name' => 'hz_NA',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 65,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'label' => 'Hindi',
                'value' => 'hi',
                'name' => 'hi_IN',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 66,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'label' => 'Hiri Motu',
                'value' => 'ho',
                'name' => 'ho_PG',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 67,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'label' => 'Hungarian',
                'value' => 'hu',
                'name' => 'hu_HU',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 68,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'label' => 'Interlingua',
                'value' => 'ia',
                'name' => 'ia_XX',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 69,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'label' => 'Indonesian',
                'value' => 'id',
                'name' => 'id_ID',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 70,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            70 => 
            array (
                'id' => 71,
                'label' => 'Interlingue',
                'value' => 'ie',
                'name' => 'ie_XX',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 71,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            71 => 
            array (
                'id' => 72,
                'label' => 'Irish',
                'value' => 'ga',
                'name' => 'ga_IE',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 72,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            72 => 
            array (
                'id' => 73,
                'label' => 'Igbo',
                'value' => 'ig',
                'name' => 'ig_NG',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 73,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            73 => 
            array (
                'id' => 74,
                'label' => 'Inupiaq',
                'value' => 'ik',
                'name' => 'ik_US',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 74,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            74 => 
            array (
                'id' => 75,
                'label' => 'Ido',
                'value' => 'io',
                'name' => 'io_XX',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 75,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            75 => 
            array (
                'id' => 76,
                'label' => 'Icelandic',
                'value' => 'is',
                'name' => 'is_IS',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 76,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            76 => 
            array (
                'id' => 77,
                'label' => 'Italian',
                'value' => 'it',
                'name' => 'it_IT',
                'is_active' => 1,
                'is_default' => 0,
                'weight' => 77,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            77 => 
            array (
                'id' => 78,
                'label' => 'Inuktitut',
                'value' => 'iu',
                'name' => 'iu_CA',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 78,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            78 => 
            array (
                'id' => 79,
                'label' => 'Japanese',
                'value' => 'ja',
                'name' => 'ja_JP',
                'is_active' => 1,
                'is_default' => 0,
                'weight' => 79,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            79 => 
            array (
                'id' => 80,
                'label' => 'Javanese',
                'value' => 'jv',
                'name' => 'jv_ID',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 80,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            80 => 
            array (
                'id' => 81,
                'label' => 'Kalaallisut, Greenlandic',
                'value' => 'kl',
                'name' => 'kl_GL',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 81,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            81 => 
            array (
                'id' => 82,
                'label' => 'Kannada',
                'value' => 'kn',
                'name' => 'kn_IN',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 82,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            82 => 
            array (
                'id' => 83,
                'label' => 'Kanuri',
                'value' => 'kr',
                'name' => 'kr_NE',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 83,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            83 => 
            array (
                'id' => 84,
                'label' => 'Kashmiri',
                'value' => 'ks',
                'name' => 'ks_IN',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 84,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            84 => 
            array (
                'id' => 85,
                'label' => 'Kazakh',
                'value' => 'kk',
                'name' => 'kk_KZ',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 85,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            85 => 
            array (
                'id' => 86,
                'label' => 'Khmer',
                'value' => 'km',
                'name' => 'km_KH',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 86,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            86 => 
            array (
                'id' => 87,
                'label' => 'Kikuyu, Gikuyu',
                'value' => 'ki',
                'name' => 'ki_KE',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 87,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            87 => 
            array (
                'id' => 88,
                'label' => 'Kinyarwanda',
                'value' => 'rw',
                'name' => 'rw_RW',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 88,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            88 => 
            array (
                'id' => 89,
                'label' => 'Kirghiz, Kyrgyz',
                'value' => 'ky',
                'name' => 'ky_KG',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 89,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            89 => 
            array (
                'id' => 90,
                'label' => 'Komi',
                'value' => 'kv',
                'name' => 'kv_RU',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 90,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            90 => 
            array (
                'id' => 91,
                'label' => 'Kongo',
                'value' => 'kg',
                'name' => 'kg_CD',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 91,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            91 => 
            array (
                'id' => 92,
                'label' => 'Korean',
                'value' => 'ko',
                'name' => 'ko_KR',
                'is_active' => 1,
                'is_default' => 0,
                'weight' => 92,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            92 => 
            array (
                'id' => 93,
                'label' => 'Kurdish',
                'value' => 'ku',
                'name' => 'ku_IQ',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 93,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            93 => 
            array (
                'id' => 94,
                'label' => 'Kwanyama, Kuanyama',
                'value' => 'kj',
                'name' => 'kj_NA',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 94,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            94 => 
            array (
                'id' => 95,
                'label' => 'Latin',
                'value' => 'la',
                'name' => 'la_VA',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 95,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            95 => 
            array (
                'id' => 96,
                'label' => 'Luxembourgish, Letzeburgesch',
                'value' => 'lb',
                'name' => 'lb_LU',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 96,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            96 => 
            array (
                'id' => 97,
                'label' => 'Luganda',
                'value' => 'lg',
                'name' => 'lg_UG',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 97,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            97 => 
            array (
                'id' => 98,
                'label' => 'Limburgish, Limburgan, Limburger',
                'value' => 'li',
                'name' => 'li_NL',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 98,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            98 => 
            array (
                'id' => 99,
                'label' => 'Lingala',
                'value' => 'ln',
                'name' => 'ln_CD',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 99,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            99 => 
            array (
                'id' => 100,
                'label' => 'Lao',
                'value' => 'lo',
                'name' => 'lo_LA',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 100,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            100 => 
            array (
                'id' => 101,
                'label' => 'Lithuanian',
                'value' => 'lt',
                'name' => 'lt_LT',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 101,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            101 => 
            array (
                'id' => 102,
                'label' => 'Luba-Katanga',
                'value' => 'lu',
                'name' => 'lu_CD',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 102,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            102 => 
            array (
                'id' => 103,
                'label' => 'Latvian',
                'value' => 'lv',
                'name' => 'lv_LV',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 103,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            103 => 
            array (
                'id' => 104,
                'label' => 'Manx',
                'value' => 'gv',
                'name' => 'gv_IM',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 104,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            104 => 
            array (
                'id' => 105,
                'label' => 'Macedonian',
                'value' => 'mk',
                'name' => 'mk_MK',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 105,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            105 => 
            array (
                'id' => 106,
                'label' => 'Malagasy',
                'value' => 'mg',
                'name' => 'mg_MG',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 106,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            106 => 
            array (
                'id' => 107,
                'label' => 'Malay',
                'value' => 'ms',
                'name' => 'ms_MY',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 107,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            107 => 
            array (
                'id' => 108,
                'label' => 'Malayalam',
                'value' => 'ml',
                'name' => 'ml_IN',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 108,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            108 => 
            array (
                'id' => 109,
                'label' => 'Maltese',
                'value' => 'mt',
                'name' => 'mt_MT',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 109,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            109 => 
            array (
                'id' => 110,
                'label' => 'Māori',
                'value' => 'mi',
                'name' => 'mi_NZ',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 110,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            110 => 
            array (
                'id' => 111,
                'label' => 'Marathi',
                'value' => 'mr',
                'name' => 'mr_IN',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 111,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            111 => 
            array (
                'id' => 112,
                'label' => 'Marshallese',
                'value' => 'mh',
                'name' => 'mh_MH',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 112,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            112 => 
            array (
                'id' => 113,
                'label' => 'Mongolian',
                'value' => 'mn',
                'name' => 'mn_MN',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 113,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            113 => 
            array (
                'id' => 114,
                'label' => 'Nauru',
                'value' => 'na',
                'name' => 'na_NR',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 114,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            114 => 
            array (
                'id' => 115,
                'label' => 'Navajo, Navaho',
                'value' => 'nv',
                'name' => 'nv_US',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 115,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            115 => 
            array (
                'id' => 116,
                'label' => 'Norwegian Bokmål',
                'value' => 'nb',
                'name' => 'nb_NO',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 116,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            116 => 
            array (
                'id' => 117,
                'label' => 'North Ndebele',
                'value' => 'nd',
                'name' => 'nd_ZW',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 117,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            117 => 
            array (
                'id' => 118,
                'label' => 'Nepali',
                'value' => 'ne',
                'name' => 'ne_NP',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 118,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            118 => 
            array (
                'id' => 119,
                'label' => 'Ndonga',
                'value' => 'ng',
                'name' => 'ng_NA',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 119,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            119 => 
            array (
                'id' => 120,
                'label' => 'Norwegian Nynorsk',
                'value' => 'nn',
                'name' => 'nn_NO',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 120,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            120 => 
            array (
                'id' => 121,
                'label' => 'Norwegian',
                'value' => 'no',
                'name' => 'no_NO',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 121,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            121 => 
            array (
                'id' => 122,
                'label' => 'Nuosu',
                'value' => 'ii',
                'name' => 'ii_CN',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 122,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            122 => 
            array (
                'id' => 123,
                'label' => 'South Ndebele',
                'value' => 'nr',
                'name' => 'nr_ZA',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 123,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            123 => 
            array (
                'id' => 124,
            'label' => 'Occitan (after 1500)',
                'value' => 'oc',
                'name' => 'oc_FR',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 124,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            124 => 
            array (
                'id' => 125,
                'label' => 'Ojibwa',
                'value' => 'oj',
                'name' => 'oj_CA',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 125,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            125 => 
            array (
                'id' => 126,
                'label' => 'Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic',
                'value' => 'cu',
                'name' => 'cu_BG',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 126,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            126 => 
            array (
                'id' => 127,
                'label' => 'Oromo',
                'value' => 'om',
                'name' => 'om_ET',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 127,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            127 => 
            array (
                'id' => 128,
                'label' => 'Oriya',
                'value' => 'or',
                'name' => 'or_IN',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 128,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            128 => 
            array (
                'id' => 129,
                'label' => 'Ossetian, Ossetic',
                'value' => 'os',
                'name' => 'os_GE',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 129,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            129 => 
            array (
                'id' => 130,
                'label' => 'Panjabi, Punjabi',
                'value' => 'pa',
                'name' => 'pa_IN',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 130,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            130 => 
            array (
                'id' => 131,
                'label' => 'Pāli',
                'value' => 'pi',
                'name' => 'pi_KH',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 131,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            131 => 
            array (
                'id' => 132,
            'label' => 'Persian (Iran)',
                'value' => 'fa',
                'name' => 'fa_IR',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 132,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            132 => 
            array (
                'id' => 133,
                'label' => 'Polish',
                'value' => 'pl',
                'name' => 'pl_PL',
                'is_active' => 1,
                'is_default' => 0,
                'weight' => 133,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            133 => 
            array (
                'id' => 134,
                'label' => 'Pashto, Pushto',
                'value' => 'ps',
                'name' => 'ps_AF',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 134,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            134 => 
            array (
                'id' => 135,
            'label' => 'Portuguese (Brazil)',
                'value' => 'pt',
                'name' => 'pt_BR',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 135,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            135 => 
            array (
                'id' => 136,
            'label' => 'Portuguese (Portugal)',
                'value' => 'pt',
                'name' => 'pt_PT',
                'is_active' => 1,
                'is_default' => 0,
                'weight' => 136,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            136 => 
            array (
                'id' => 137,
                'label' => 'Quechua',
                'value' => 'qu',
                'name' => 'qu_PE',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 137,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            137 => 
            array (
                'id' => 138,
                'label' => 'Romansh',
                'value' => 'rm',
                'name' => 'rm_CH',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 138,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            138 => 
            array (
                'id' => 139,
                'label' => 'Kirundi',
                'value' => 'rn',
                'name' => 'rn_BI',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 139,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            139 => 
            array (
                'id' => 140,
                'label' => 'Romanian, Moldavian, Moldovan',
                'value' => 'ro',
                'name' => 'ro_RO',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 140,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            140 => 
            array (
                'id' => 141,
                'label' => 'Russian',
                'value' => 'ru',
                'name' => 'ru_RU',
                'is_active' => 1,
                'is_default' => 0,
                'weight' => 141,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            141 => 
            array (
                'id' => 142,
                'label' => 'Sanskrit',
                'value' => 'sa',
                'name' => 'sa_IN',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 142,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            142 => 
            array (
                'id' => 143,
                'label' => 'Sardinian',
                'value' => 'sc',
                'name' => 'sc_IT',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 143,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            143 => 
            array (
                'id' => 144,
                'label' => 'Sindhi',
                'value' => 'sd',
                'name' => 'sd_IN',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 144,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            144 => 
            array (
                'id' => 145,
                'label' => 'Northern Sami',
                'value' => 'se',
                'name' => 'se_NO',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 145,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            145 => 
            array (
                'id' => 146,
                'label' => 'Samoan',
                'value' => 'sm',
                'name' => 'sm_WS',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 146,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            146 => 
            array (
                'id' => 147,
                'label' => 'Sango',
                'value' => 'sg',
                'name' => 'sg_CF',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 147,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            147 => 
            array (
                'id' => 148,
                'label' => 'Serbian',
                'value' => 'sr',
                'name' => 'sr_RS',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 148,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            148 => 
            array (
                'id' => 149,
                'label' => 'Scottish Gaelic; Gaelic',
                'value' => 'gd',
                'name' => 'gd_GB',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 149,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            149 => 
            array (
                'id' => 150,
                'label' => 'Shona',
                'value' => 'sn',
                'name' => 'sn_ZW',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 150,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            150 => 
            array (
                'id' => 151,
                'label' => 'Sinhala, Sinhalese',
                'value' => 'si',
                'name' => 'si_LK',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 151,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            151 => 
            array (
                'id' => 152,
                'label' => 'Slovak',
                'value' => 'sk',
                'name' => 'sk_SK',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 152,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            152 => 
            array (
                'id' => 153,
                'label' => 'Slovene',
                'value' => 'sl',
                'name' => 'sl_SI',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 153,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            153 => 
            array (
                'id' => 154,
                'label' => 'Somali',
                'value' => 'so',
                'name' => 'so_SO',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 154,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            154 => 
            array (
                'id' => 155,
                'label' => 'Southern Sotho',
                'value' => 'st',
                'name' => 'st_ZA',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 155,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            155 => 
            array (
                'id' => 156,
            'label' => 'Spanish; Castilian (Spain)',
                'value' => 'es',
                'name' => 'es_ES',
                'is_active' => 1,
                'is_default' => 0,
                'weight' => 156,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            156 => 
            array (
                'id' => 157,
            'label' => 'Spanish; Castilian (Mexico)',
                'value' => 'es',
                'name' => 'es_MX',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 157,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            157 => 
            array (
                'id' => 158,
            'label' => 'Spanish; Castilian (Puerto Rico)',
                'value' => 'es',
                'name' => 'es_PR',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 158,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            158 => 
            array (
                'id' => 159,
                'label' => 'Sundanese',
                'value' => 'su',
                'name' => 'su_ID',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 159,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            159 => 
            array (
                'id' => 160,
                'label' => 'Swahili',
                'value' => 'sw',
                'name' => 'sw_TZ',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 160,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            160 => 
            array (
                'id' => 161,
                'label' => 'Swati',
                'value' => 'ss',
                'name' => 'ss_ZA',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 161,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            161 => 
            array (
                'id' => 162,
                'label' => 'Swedish',
                'value' => 'sv',
                'name' => 'sv_SE',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 162,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            162 => 
            array (
                'id' => 163,
                'label' => 'Tamil',
                'value' => 'ta',
                'name' => 'ta_IN',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 163,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            163 => 
            array (
                'id' => 164,
                'label' => 'Telugu',
                'value' => 'te',
                'name' => 'te_IN',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 164,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            164 => 
            array (
                'id' => 165,
                'label' => 'Tajik',
                'value' => 'tg',
                'name' => 'tg_TJ',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 165,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            165 => 
            array (
                'id' => 166,
                'label' => 'Thai',
                'value' => 'th',
                'name' => 'th_TH',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 166,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            166 => 
            array (
                'id' => 167,
                'label' => 'Tigrinya',
                'value' => 'ti',
                'name' => 'ti_ET',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 167,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            167 => 
            array (
                'id' => 168,
                'label' => 'Tibetan Standard, Tibetan, Central',
                'value' => 'bo',
                'name' => 'bo_CN',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 168,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            168 => 
            array (
                'id' => 169,
                'label' => 'Turkmen',
                'value' => 'tk',
                'name' => 'tk_TM',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 169,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            169 => 
            array (
                'id' => 170,
                'label' => 'Tagalog',
                'value' => 'tl',
                'name' => 'tl_PH',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 170,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            170 => 
            array (
                'id' => 171,
                'label' => 'Tswana',
                'value' => 'tn',
                'name' => 'tn_ZA',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 171,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            171 => 
            array (
                'id' => 172,
            'label' => 'Tonga (Tonga Islands)',
                'value' => 'to',
                'name' => 'to_TO',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 172,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            172 => 
            array (
                'id' => 173,
                'label' => 'Turkish',
                'value' => 'tr',
                'name' => 'tr_TR',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 173,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            173 => 
            array (
                'id' => 174,
                'label' => 'Tsonga',
                'value' => 'ts',
                'name' => 'ts_ZA',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 174,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            174 => 
            array (
                'id' => 175,
                'label' => 'Tatar',
                'value' => 'tt',
                'name' => 'tt_RU',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 175,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            175 => 
            array (
                'id' => 176,
                'label' => 'Twi',
                'value' => 'tw',
                'name' => 'tw_GH',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 176,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            176 => 
            array (
                'id' => 177,
                'label' => 'Tahitian',
                'value' => 'ty',
                'name' => 'ty_PF',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 177,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            177 => 
            array (
                'id' => 178,
                'label' => 'Uighur, Uyghur',
                'value' => 'ug',
                'name' => 'ug_CN',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 178,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            178 => 
            array (
                'id' => 179,
                'label' => 'Ukrainian',
                'value' => 'uk',
                'name' => 'uk_UA',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 179,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            179 => 
            array (
                'id' => 180,
                'label' => 'Urdu',
                'value' => 'ur',
                'name' => 'ur_PK',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 180,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            180 => 
            array (
                'id' => 181,
                'label' => 'Uzbek',
                'value' => 'uz',
                'name' => 'uz_UZ',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 181,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            181 => 
            array (
                'id' => 182,
                'label' => 'Venda',
                'value' => 've',
                'name' => 've_ZA',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 182,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            182 => 
            array (
                'id' => 183,
                'label' => 'Vietnamese',
                'value' => 'vi',
                'name' => 'vi_VN',
                'is_active' => 1,
                'is_default' => 0,
                'weight' => 183,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            183 => 
            array (
                'id' => 184,
                'label' => 'Volapük',
                'value' => 'vo',
                'name' => 'vo_XX',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 184,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            184 => 
            array (
                'id' => 185,
                'label' => 'Walloon',
                'value' => 'wa',
                'name' => 'wa_BE',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 185,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            185 => 
            array (
                'id' => 186,
                'label' => 'Welsh',
                'value' => 'cy',
                'name' => 'cy_GB',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 186,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            186 => 
            array (
                'id' => 187,
                'label' => 'Wolof',
                'value' => 'wo',
                'name' => 'wo_SN',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 187,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            187 => 
            array (
                'id' => 188,
                'label' => 'Western Frisian',
                'value' => 'fy',
                'name' => 'fy_NL',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 188,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            188 => 
            array (
                'id' => 189,
                'label' => 'Xhosa',
                'value' => 'xh',
                'name' => 'xh_ZA',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 189,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            189 => 
            array (
                'id' => 190,
                'label' => 'Yiddish',
                'value' => 'yi',
                'name' => 'yi_US',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 190,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            190 => 
            array (
                'id' => 191,
                'label' => 'Yoruba',
                'value' => 'yo',
                'name' => 'yo_NG',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 191,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            191 => 
            array (
                'id' => 192,
                'label' => 'Zhuang, Chuang',
                'value' => 'za',
                'name' => 'za_CN',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 192,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            192 => 
            array (
                'id' => 193,
                'label' => 'Zulu',
                'value' => 'zu',
                'name' => 'zu_ZA',
                'is_active' => 0,
                'is_default' => 0,
                'weight' => 193,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}