<?php

use Illuminate\Database\Seeder;

class ParticipantRoleTypeTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('participant_role_type')->delete();
        
        \DB::table('participant_role_type')->insert(array (
            0 => 
            array (
                'id' => 1,
                'option_group_id' => 13,
                'label' => 'Attendee',
                'value' => '1',
                'name' => 'Attendee',
                'grouping' => NULL,
                'filter' => 1,
                'is_default' => NULL,
                'weight' => 1,
                'description' => NULL,
                'is_optgroup' => 0,
                'is_reserved' => 0,
                'is_active' => 1,
                'component_id' => NULL,
                'domain_id' => NULL,
                'visibility_id' => NULL,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'option_group_id' => 13,
                'label' => 'Volunteer',
                'value' => '2',
                'name' => 'Volunteer',
                'grouping' => NULL,
                'filter' => 1,
                'is_default' => NULL,
                'weight' => 2,
                'description' => NULL,
                'is_optgroup' => 0,
                'is_reserved' => 0,
                'is_active' => 1,
                'component_id' => NULL,
                'domain_id' => NULL,
                'visibility_id' => NULL,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'option_group_id' => 13,
                'label' => 'Host',
                'value' => '3',
                'name' => 'Host',
                'grouping' => NULL,
                'filter' => 1,
                'is_default' => NULL,
                'weight' => 3,
                'description' => NULL,
                'is_optgroup' => 0,
                'is_reserved' => 0,
                'is_active' => 1,
                'component_id' => NULL,
                'domain_id' => NULL,
                'visibility_id' => NULL,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'option_group_id' => 13,
                'label' => 'Speaker',
                'value' => '4',
                'name' => 'Speaker',
                'grouping' => NULL,
                'filter' => 1,
                'is_default' => NULL,
                'weight' => 4,
                'description' => NULL,
                'is_optgroup' => 0,
                'is_reserved' => 0,
                'is_active' => 1,
                'component_id' => NULL,
                'domain_id' => NULL,
                'visibility_id' => NULL,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'option_group_id' => 13,
                'label' => 'Retreatant',
                'value' => '5',
                'name' => 'Retreatant',
                'grouping' => NULL,
                'filter' => 1,
                'is_default' => NULL,
                'weight' => 5,
                'description' => '<p>a person making the SpEx</p>
',
                'is_optgroup' => 0,
                'is_reserved' => 0,
                'is_active' => 1,
                'component_id' => NULL,
                'domain_id' => NULL,
                'visibility_id' => NULL,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => 8,
                'option_group_id' => 13,
                'label' => 'Retreat Director',
                'value' => 'Retreat Director',
                'name' => 'Retreat Director',
                'grouping' => NULL,
                'filter' => 1,
                'is_default' => 0,
                'weight' => 6,
                'description' => 'Retreat Director',
                'is_optgroup' => 0,
                'is_reserved' => 0,
                'is_active' => 1,
                'component_id' => NULL,
                'domain_id' => NULL,
                'visibility_id' => NULL,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 9,
                'option_group_id' => 13,
                'label' => 'Innkeeper',
                'value' => 'Innkeeper',
                'name' => 'Innkeeper',
                'grouping' => NULL,
                'filter' => 1,
                'is_default' => 0,
                'weight' => 7,
                'description' => 'Innkeeper',
                'is_optgroup' => 0,
                'is_reserved' => 0,
                'is_active' => 1,
                'component_id' => NULL,
                'domain_id' => NULL,
                'visibility_id' => NULL,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'id' => 10,
                'option_group_id' => 13,
                'label' => 'Assistant',
                'value' => 'Assistant',
                'name' => 'Assistant',
                'grouping' => NULL,
                'filter' => 1,
                'is_default' => 0,
                'weight' => 8,
                'description' => 'Assistant',
                'is_optgroup' => 0,
                'is_reserved' => 0,
                'is_active' => 1,
                'component_id' => NULL,
                'domain_id' => NULL,
                'visibility_id' => NULL,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'id' => 11,
                'option_group_id' => 13,
                'label' => 'Captain',
                'value' => 'Captain',
                'name' => 'Captain',
                'grouping' => NULL,
                'filter' => NULL,
                'is_default' => 0,
                'weight' => 9,
                'description' => 'Captain',
                'is_optgroup' => 0,
                'is_reserved' => 0,
                'is_active' => 1,
                'component_id' => NULL,
                'domain_id' => NULL,
                'visibility_id' => NULL,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}