<?php

use Illuminate\Database\Seeder;

class ParticipantStatusTypeTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('participant_status_type')->delete();
        
        \DB::table('participant_status_type')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Registered',
                'label' => 'Registered',
                'value' => NULL,
                'class' => 'Positive',
                'is_reserved' => 1,
                'is_active' => 1,
                'is_counted' => 1,
                'weight' => 1,
                'visibility_id' => 1,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Attended',
                'label' => 'Attended',
                'value' => NULL,
                'class' => 'Positive',
                'is_reserved' => 0,
                'is_active' => 1,
                'is_counted' => 1,
                'weight' => 2,
                'visibility_id' => 2,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'No-show',
                'label' => 'No-show',
                'value' => NULL,
                'class' => 'Negative',
                'is_reserved' => 0,
                'is_active' => 1,
                'is_counted' => 0,
                'weight' => 3,
                'visibility_id' => 2,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Cancelled',
                'label' => 'Cancelled',
                'value' => NULL,
                'class' => 'Negative',
                'is_reserved' => 1,
                'is_active' => 1,
                'is_counted' => 0,
                'weight' => 4,
                'visibility_id' => 2,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Pending from pay later',
                'label' => 'Pending from pay later',
                'value' => NULL,
                'class' => 'Pending',
                'is_reserved' => 1,
                'is_active' => 0,
                'is_counted' => 1,
                'weight' => 5,
                'visibility_id' => 2,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Pending from incomplete transaction',
                'label' => 'Pending from incomplete transaction',
                'value' => NULL,
                'class' => 'Pending',
                'is_reserved' => 1,
                'is_active' => 0,
                'is_counted' => 0,
                'weight' => 6,
                'visibility_id' => 2,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'On waitlist',
                'label' => 'Waitlist',
                'value' => NULL,
                'class' => 'Waiting',
                'is_reserved' => 1,
                'is_active' => 1,
                'is_counted' => 0,
                'weight' => 7,
                'visibility_id' => 2,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Awaiting approval',
                'label' => 'Awaiting approval',
                'value' => NULL,
                'class' => 'Waiting',
                'is_reserved' => 1,
                'is_active' => 0,
                'is_counted' => 1,
                'weight' => 8,
                'visibility_id' => 2,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Pending from waitlist',
                'label' => 'Pending from waitlist',
                'value' => NULL,
                'class' => 'Pending',
                'is_reserved' => 1,
                'is_active' => 0,
                'is_counted' => 1,
                'weight' => 9,
                'visibility_id' => 2,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Pending from approval',
                'label' => 'Pending from approval',
                'value' => NULL,
                'class' => 'Pending',
                'is_reserved' => 1,
                'is_active' => 0,
                'is_counted' => 1,
                'weight' => 10,
                'visibility_id' => 2,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'Rejected',
                'label' => 'Rejected',
                'value' => NULL,
                'class' => 'Negative',
                'is_reserved' => 1,
                'is_active' => 0,
                'is_counted' => 0,
                'weight' => 11,
                'visibility_id' => 2,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'Expired',
                'label' => 'Expired',
                'value' => NULL,
                'class' => 'Negative',
                'is_reserved' => 1,
                'is_active' => 0,
                'is_counted' => 0,
                'weight' => 12,
                'visibility_id' => 2,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'Pending in cart',
                'label' => 'Pending in cart',
                'value' => NULL,
                'class' => 'Pending',
                'is_reserved' => 1,
                'is_active' => 0,
                'is_counted' => 0,
                'weight' => 13,
                'visibility_id' => 2,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Course Completed',
                'label' => 'Course Completed',
                'value' => NULL,
                'class' => 'Positive',
                'is_reserved' => NULL,
                'is_active' => 0,
                'is_counted' => 0,
                'weight' => 14,
                'visibility_id' => 2,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'Withdrew',
                'label' => 'Withdrew',
                'value' => NULL,
                'class' => 'Positive',
                'is_reserved' => NULL,
                'is_active' => 0,
                'is_counted' => 0,
                'weight' => 15,
                'visibility_id' => 2,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'Ongoing Retreat',
                'label' => 'Ongoing Retreatant',
                'value' => NULL,
                'class' => 'Positive',
                'is_reserved' => NULL,
                'is_active' => 0,
                'is_counted' => 0,
                'weight' => 16,
                'visibility_id' => 2,
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}