<?php

/* @var $factory \Illuminate\Database\Eloquent\Factory */

use Faker\Generator as Faker;

$factory->define(App\Donor::class, function (Faker $faker) {
    return [
        'donor_id' => $faker->randomNumber(5),
        'FName' => $faker->word,
        'MInitial' => $faker->word,
        'LName' => $faker->word,
        'Address' => $faker->word,
        'Address2' => $faker->word,
        'City' => $faker->word,
        'State' => $faker->word,
        'Zip' => $faker->word,
        'NickName' => $faker->word,
        'SpouseName' => $faker->word,
        'HomePhone' => $faker->word,
        'WorkPhone' => $faker->word,
        'EMailAddress' => $faker->word,
        'FaxNumber' => $faker->word,
        'worker_id' => $faker->randomNumber(),
        'city_id' => $faker->randomNumber(),
        'phase_id' => $faker->randomNumber(),
        'age_id' => $faker->randomNumber(),
        'occup_id' => $faker->randomNumber(),
        'church_id' => $faker->randomNumber(),
        'salut_id' => $faker->randomNumber(),
        'NameEnd' => $faker->word,
        'Gender' => $faker->word,
        'donation_type_id' => $faker->randomNumber(),
        'DonationID' => $faker->randomNumber(),
        'retreat_id' => $faker->randomNumber(),
        'retreat_date' => $faker->dateTime(),
        'First Visit' => $faker->word,
        'Big Donor' => $faker->word,
        'Old Donor' => $faker->word,
        'New Date ID' => $faker->randomNumber(),
        'NotAvailable' => $faker->word,
        'Note' => $faker->word,
        'CampLetterSent' => $faker->word,
        'DateLetSent' => $faker->dateTime(),
        'AdventDonor' => $faker->word,
        'Church' => $faker->word,
        'Elderhostel' => $faker->word,
        'Deceased' => $faker->word,
        'Spouse' => $faker->word,
        'RoomNum' => $faker->word,
        'Cancel' => $faker->word,
        'ReqRemoval' => $faker->word,
        'Note1' => $faker->word,
        'Note2' => $faker->text,
        'BoardMember' => $faker->word,
        'NoticeSend' => $faker->word,
        'Ambassador' => $faker->word,
        'Knights' => $faker->word,
        'AmbassadorSince' => $faker->word,
        'ParkCityClub' => $faker->word,
        'SpeedwayClub' => $faker->word,
        'DonatedWillNotAttend' => $faker->word,
        'PartyMailList' => $faker->word,
        'SpiritDirect' => $faker->word,
        'KofC Grand Councils' => $faker->word,
        'Hispanic' => $faker->word,
        'October Dinner Meeting' => $faker->word,
        'Board Advisor' => $faker->word,
        'cell_phone' => $faker->word,
        'Emergency Contact Num' => $faker->word,
        'Emergency Name' => $faker->word,
        'Emergency Contact Num2' => $faker->word,
        'St Rita Spiritual Exercises' => $faker->word,
        'contact_id' => $faker->randomNumber(),
        'sort_name' => $faker->word,
        'sort_name_count' => $faker->randomNumber(2),
    ];
});
