<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\DioceseController
 */
class DioceseControllerTest extends TestCase
{
    // use RefreshDatabase;

    /**
     * @test
     */
    public function create_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(\App\User::class)->create();

        $response = $this->actingAs($user)->get(route('diocese.create'));

        $response->assertOk();
        $response->assertViewIs('dioceses.create');
        $response->assertViewHas('bishops');
        $response->assertViewHas('states');
        $response->assertViewHas('countries');
        $response->assertViewHas('defaults');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function destroy_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $diocese = factory(\App\Diocese::class)->create();
        $user = factory(\App\User::class)->create();

        $response = $this->actingAs($user)->delete(route('diocese.destroy', [$diocese]));

        $response->assertRedirect(action('DioceseController@index'));
        $this->assertDeleted($diocese);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function edit_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $diocese = factory(\App\Diocese::class)->create();
        $user = factory(\App\User::class)->create();

        $response = $this->actingAs($user)->get(route('diocese.edit', [$diocese]));

        $response->assertOk();
        $response->assertViewIs('dioceses.edit');
        $response->assertViewHas('diocese');
        $response->assertViewHas('bishops');
        $response->assertViewHas('states');
        $response->assertViewHas('countries');
        $response->assertViewHas('defaults');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(\App\User::class)->create();

        $response = $this->actingAs($user)->get(route('diocese.index'));

        $response->assertOk();
        $response->assertViewIs('dioceses.index');
        $response->assertViewHas('dioceses');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function show_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $diocese = factory(\App\Diocese::class)->create();
        $user = factory(\App\User::class)->create();

        $response = $this->actingAs($user)->get(route('diocese.show', [$diocese]));

        $response->assertOk();
        $response->assertViewIs('dioceses.show');
        $response->assertViewHas('diocese');
        $response->assertViewHas('relationship_types');
        $response->assertViewHas('files');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(\App\User::class)->create();

        $response = $this->actingAs($user)->post(route('diocese.store'), [
            // TODO: send request data
        ]);

        $response->assertRedirect(action('DioceseController@index'));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\DioceseController::class,
            'store',
            \App\Http\Requests\StoreDioceseRequest::class
        );
    }

    /**
     * @test
     */
    public function update_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $diocese = factory(\App\Diocese::class)->create();
        $user = factory(\App\User::class)->create();

        $response = $this->actingAs($user)->put(route('diocese.update', [$diocese]), [
            // TODO: send request data
        ]);

        $response->assertRedirect(action('DioceseController@show', $diocese->id));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function update_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\DioceseController::class,
            'update',
            \App\Http\Requests\UpdateDioceseRequest::class
        );
    }

    // test cases...
}
