<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\GateController
 */
class GateControllerTest extends TestCase
{
    /**
     * @test
     */
    public function close_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(\App\User::class)->create();

        $response = $this->actingAs($user)->get(route('gate.close'));

        $response->assertOk();
        $response->assertViewIs('gate.close');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function open_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(\App\User::class)->create();

        $response = $this->actingAs($user)->get(route('gate.open'));

        $response->assertOk();
        $response->assertViewIs('gate.open');
        $response->assertViewHas('hours');

        // TODO: perform additional assertions
    }

    // test cases...
}
