<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\MailgunController
 */
class MailgunControllerTest extends TestCase
{
    /**
     * @test
     */
    public function get_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(\App\User::class)->create();

        $response = $this->actingAs($user)->get(route('mailgun.get'));

        $response->assertOk();
        $response->assertViewIs('mailgun.index');
        $response->assertViewHas('messages');
        $response->assertViewHas('staff');
        $response->assertViewHas('contact');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function process_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(\App\User::class)->create();

        $response = $this->actingAs($user)->get(route('mailgun.process'));

        $response->assertOk();
        $response->assertViewIs('mailgun.processed');
        $response->assertViewHas('messages');

        // TODO: perform additional assertions
    }

    // test cases...
}
