<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\RoomController
 */
class RoomControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function create_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(\App\User::class)->create();

        $response = $this->actingAs($user)->get(route('room.create'));

        $response->assertOk();
        $response->assertViewIs('rooms.create');
        $response->assertViewHas('locations');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function destroy_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $room = factory(\App\Room::class)->create();
        $user = factory(\App\User::class)->create();

        $response = $this->actingAs($user)->delete(route('room.destroy', [$room]));

        $response->assertRedirect(action('RoomController@index'));
        $this->assertDeleted($room);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function edit_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $room = factory(\App\Room::class)->create();
        $user = factory(\App\User::class)->create();

        $response = $this->actingAs($user)->get(route('room.edit', [$room]));

        $response->assertOk();
        $response->assertViewIs('rooms.edit');
        $response->assertViewHas('room');
        $response->assertViewHas('locations');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(\App\User::class)->create();

        $response = $this->actingAs($user)->get(route('room.index'));

        $response->assertOk();
        $response->assertViewIs('rooms.index');
        $response->assertViewHas('roomsort');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function schedule_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(\App\User::class)->create();

        $response = $this->actingAs($user)->get(route('rooms'));

        $response->assertOk();
        $response->assertViewIs('404');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function show_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $room = factory(\App\Room::class)->create();
        $user = factory(\App\User::class)->create();

        $response = $this->actingAs($user)->get(route('room.show', [$room]));

        $response->assertOk();
        $response->assertViewIs('rooms.show');
        $response->assertViewHas('room');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(\App\User::class)->create();

        $response = $this->actingAs($user)->post(route('room.store'), [
            // TODO: send request data
        ]);

        $response->assertRedirect(action('RoomController@index'));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\RoomController::class,
            'store',
            \App\Http\Requests\StoreRoomRequest::class
        );
    }

    /**
     * @test
     */
    public function update_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $room = factory(\App\Room::class)->create();
        $user = factory(\App\User::class)->create();

        $response = $this->actingAs($user)->put(route('room.update', [$room]), [
            // TODO: send request data
        ]);

        $response->assertRedirect(action('RoomController@index'));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function update_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\RoomController::class,
            'update',
            \App\Http\Requests\UpdateRoomRequest::class
        );
    }

    // test cases...
}
