<?php
define('RELATIONSHIP_TYPE_CHILD_PARENT', 1);
define('RELATIONSHIP_TYPE_HUSBAND_WIFE', 2);
define('RELATIONSHIP_TYPE_SIBLING', 4);
define('RELATIONSHIP_TYPE_STAFF', 5);
define('RELATIONSHIP_TYPE_VOLUNTEER', 6);
define('RELATIONSHIP_TYPE_PARISHIONER', 11);
define('RELATIONSHIP_TYPE_BISHOP', 12);
define('RELATIONSHIP_TYPE_DIOCESE', 13);
define('RELATIONSHIP_TYPE_PASTOR', 14);
define('RELATIONSHIP_TYPE_SUPERIOR', 15);
define('RELATIONSHIP_TYPE_PROVINCIAL', 16);
define('RELATIONSHIP_TYPE_COMMUNITY_MEMBER', 17);
define('RELATIONSHIP_TYPE_BOARD_MEMBER', 18);
define('RELATIONSHIP_TYPE_RETREAT_DIRECTOR', 19);
define('RELATIONSHIP_TYPE_RETREAT_ASSISTANT', 20);
define('RELATIONSHIP_TYPE_RETREAT_INNKEEPER', 21);
define('RELATIONSHIP_TYPE_RETREATANT', 22);
define('RELATIONSHIP_TYPE_DONOR', 23);
define('RELATIONSHIP_TYPE_CAPTAIN', 24);
define('RELATIONSHIP_TYPE_PRIEST', 25);
define('RELATIONSHIP_TYPE_DEACON', 26);


define('CONTACT_TYPE_INDIVIDUAL', 1);
define('CONTACT_TYPE_HOUSEHOLD', 2);
define('CONTACT_TYPE_ORGANIZATION', 3);
define('CONTACT_TYPE_PARISH', 4);
define('CONTACT_TYPE_DIOCESE', 5);
define('CONTACT_TYPE_PROVINCE', 6);
define('CONTACT_TYPE_COMMUNITY', 7);
define('CONTACT_TYPE_RETREAT_HOUSE', 8);
define('CONTACT_TYPE_VENDOR', 9);
define('CONTACT_TYPE_RELIGIOUS_CATHOLIC', 10);
define('CONTACT_TYPE_RELIGIOUS_NONCATHOLIC', 11);
define('CONTACT_TYPE_CONTRACT', 12);
define('CONTACT_TYPE_FOUNDATION', 13);

define('COUNTRY_ID_USA', 1228);
define('STATE_PROVINCE_ID_TX', 1042);

define('LOCATION_TYPE_HOME', 1);
define('LOCATION_TYPE_WORK', 2);
define('LOCATION_TYPE_MAIN', 3);
define('LOCATION_TYPE_OTHER', 4);
define('LOCATION_TYPE_BILLING', 5);

define('CONTACT_DIOCESE_DALLAS', 3);
define('CONTACT_DIOCESE_FORTWORTH', 1);
define('CONTACT_DIOCESE_TYLER', 2);
define('CONTACT_MONTSERRAT', 620);

define('EVENT_TYPE_CONFERENCE', 1);
define('EVENT_TYPE_EXHIBITION', 2);
define('EVENT_TYPE_FUNDRAISER', 3);
define('EVENT_TYPE_MEETING', 4);
define('EVENT_TYPE_PERFORMANCE', 5);
define('EVENT_TYPE_WORKSHOP', 6);
define('EVENT_TYPE_IGNATIAN', 7);
define('EVENT_TYPE_DIOCESAN', 8);
define('EVENT_TYPE_OTHER', 9);
define('EVENT_TYPE_DAY', 10);
define('EVENT_TYPE_CONTRACT', 11);
define('EVENT_TYPE_DIRECTED', 12);


define('FILE_TYPE_CONTACT_ATTACHMENT', 1);
define('FILE_TYPE_EVENT_SCHEDULE', 2);
define('FILE_TYPE_EVENT_EVALUATION', 3);
define('FILE_TYPE_EVENT_CONTRACT', 4);
define('FILE_TYPE_EVENT_GROUP_PHOTO', 5);
define('FILE_TYPE_CONTACT_AVATAR', 6);


define('GROUP_ID_INNKEEPER', 1);
define('GROUP_ID_DIRECTOR', 2);
define('GROUP_ID_ASSISTANT', 3);
define('GROUP_ID_BISHOP', 4);
define('GROUP_ID_PRIEST', 5);
define('GROUP_ID_DEACON', 6);
define('GROUP_ID_JESUIT', 7);
define('GROUP_ID_PROVINCIAL', 8);
define('GROUP_ID_SUPERIOR', 9);
define('GROUP_ID_PASTOR', 10);
define('GROUP_ID_CAPTAIN', 11);
define('GROUP_ID_BOARD', 12);
define('GROUP_ID_STAFF', 13);
define('GROUP_ID_STEWARD', 15);
define('GROUP_ID_VOLUNTEER', 14);

define('PARTICIPANT_ROLE_ID_CAPTAIN', 11);
define('PARTICIPANT_ROLE_ID_RETREATANT', 5);
define('PARTICIPANT_ROLE_ID_RETREAT_DIRECTOR', 8);
define('PARTICIPANT_ROLE_ID_RETREAT_INNKEEPER', 9);
define('PARTICIPANT_ROLE_ID_RETREAT_ASSISTANT', 10);
